mytardis/mytardis

tardis/tardis_portal/static/js/facility_view.js, tardis/tardis_portal/templates/tardis_portal/facility_overview.html, tardis/tardis_portal/views.py, tardis/urls.py
This follows on from closed pull request #352, but is branched.
=> Facility view improvements

tardis/tardis_portal/api.py, tardis/tardis_portal/migrations/0035_remove_storage_boxes_from_datasets.py, tardis/tardis_portal/models/datafile.py, tardis/tardis_portal/models/dataset.py, tardis/tardis_portal/models/storage.py, tardis/tardis_portal/tests/filters/test_jeolsem.py, tardis/tardis_portal/tests/filters/test_middleware.py, tardis/tardis_portal/tests/test_download.py, tardis/tardis_portal/tests/test_models.py, tardis/tardis_portal/tests/test_parametersetmanager.py, tardis/tardis_portal/tests/test_staging.py
Removed storage_box field from dataset as it is not strictly necessary and causes unnecessary sync complexity
=> Refinement of storage box handling

tardis/tardis_portal/models/datafile.py, tardis/tardis_portal/templates/tardis_portal/facility_overview.html, tardis/tardis_portal/views.py
verified property of DataFile model now returns False if a
datafile doesn't have any DataFileObjects.
=> Facility overview now shows verification status of datafiles.

tardis/tardis_portal/views.py
=> changed experiment ordering from newest to oldest

tardis/tardis_portal/migrations/0033_parameter_for_links.py, tardis/tardis_portal/migrations/0037_parameter_for_links.py, tardis/tardis_portal/models/datafile.py, tardis/tardis_portal/models/parameters.py, tardis/tardis_portal/storage/squashfs.py
SquashFS storage box and example parser app to ingest and match squashfs files generated at the Australian Synchrotron
Also comes with a new parameter type that is a generic foreign key
=> linking parameters Squashfs and synchrotron parser

tardis/apps/publication_forms/static/publication-form/publication_form.css, tardis/apps/publication_forms/static/publication-form/publication_form.js, tardis/apps/publication_forms/templates/form.html
This should go some of the way to solving the problem of distinguishing datasets of the same name by showing the directory of the dataset.
=> Pub form ux enhancements

tardis/settings_changeme.py, tardis/tardis_portal/templates/tardis_portal/about.html
=> made the version info a bit prettier

tardis/tardis_portal/models/datafile.py, tardis/tardis_portal/models/storage.py
move and copy functions between storage boxes
=> File operations

tardis/apps/publication_forms/utils.py
changes to the PDBHelper class now successfully parse PDBs identified by David to fail.
=> Pub form updates

tardis/tardis_portal/api.py, tardis/urls.py
Previous pull requests attempting to merge API changes required for MyData into MyTardis were probably too complicated, so never got merged.  So now I'm trying to break down the changes into simple chunks.
Currently, this pull request only contains the ObjectACL changes I've made to the API and a fix for a possible refactoring bug.
Please let me know if you'd like me to continue adding to this pull request (e.g. API changes related to the Instrument model, API changes related to the Facility model etc.)
I'm not planning on including the API changes related to the Uploader models in this pull request, because they can go in a separate MyData app.  Also, I won't include any of the changes I made to support uploads via staging.
=> James api changes

tardis/tardis_portal/api.py, tardis/tardis_portal/tests/test_api.py, tardis/urls.py
in api.py, so InstrumentResource can reference it and then
DatasetResource can reference InstrumentResource.  Removed
storage_boxes foreign key from DatasetResource.  Added some tests
which demonstrate a few ways to interact with the Instrument
model via the API.
=> Added Instrument model to API.  Moved FacilityResource to earlier

tardis/urls.py
Implementing APIs under `/api/v1` for apps
=> app api autoloading

tardis/tardis_portal/views.py
Changed to Experiment.DoesNotExist
=> Was using ObjectDoesNotExist but import was missing.

tardis/tardis_portal/api.py, tardis/tardis_portal/models/datafile.py, tardis/tardis_portal/models/storage.py
please have a look if this would work for you @wettenhj 
Thanks
=> consolidate URI creation for staging and other uses

tardis/tardis_portal/models/datafile.py
should solve #447. Does it, @wettenhj ?
=> only copy verified files

tardis/tardis_portal/api.py
call the api endpoint `/api/v1/dataset_file/123/verify` to verify file with id 123
=> api trigger for file verifications

tardis/settings_changeme.py, tardis/tardis_portal/context_processors.py, tardis/tardis_portal/templates/tardis_portal/index.html, tardis/tardis_portal/templates/tardis_portal/login.html, tardis/tardis_portal/templates/tardis_portal/portal_template.html, tardis/tardis_portal/views.py
* Setting to disable user registration.
* Setting to disable user account management.
* Use AAF Rapid Connect URL for login button.
And also:
* Instead of raising a ValueError on a replay attack, wipe the session info, log it, and redirect the user to the front page.
=> UI tweaks for AAF mode.

tardis/tardis_portal/admin.py, tardis/tardis_portal/api.py, tardis/tardis_portal/auth/authservice.py, tardis/tardis_portal/filters/__init__.py, tardis/tardis_portal/filters/jeolsem.py, tardis/tardis_portal/models/access_control.py, tardis/tardis_portal/models/datafile.py, tardis/tardis_portal/models/experiment.py, tardis/tardis_portal/models/hooks.py, tardis/tardis_portal/models/parameters.py, tardis/tardis_portal/publish/publishservice.py, tardis/tardis_portal/tests/filters/test_middleware.py, tardis/tardis_portal/tests/test_iiif.py, tardis/tardis_portal/util.py, tardis/tardis_portal/views.py
As discussed earlier today with @wettenhj and @jasonrig
=> check for changes before calling verify

tardis/tardis_portal/sftp.py
just wondering whether an HTML entity makes sense as a replacement or whether there are better options...
=> proposed fix for slashes in names breaking sftp

tardis/settings_changeme.py, tardis/tardis_portal/models/datafile.py, tardis/tardis_portal/models/dataset.py, tardis/tardis_portal/models/experiment.py
a negative impact on performance.  See:
https://github.com/mytardis/mytardis/issues/491
=> Setting to prevent large image file processing by iiif.py from having

tardis/apps/push_to/models.py
admin forms added only when app is installed.
=> fixed admin config when push_to not installed

tardis/apps/push_to/models.py
This should suppress the warning about a missing migration.
=> refactor KeyPair public key validation

tardis/apps/anzsrc_codes/views.py, tardis/apps/equipment/views.py, tardis/apps/filepicker/views.py, tardis/apps/mx_views/views.py, tardis/apps/related_info/views.py, tardis/apps/slideshow_view/views.py, tardis/settings_changeme.py, tardis/tardis_portal/models/datafile.py, tardis/tardis_portal/models/storage.py, tardis/tardis_portal/templates/tardis_portal/ajax/parameter_table.html, tardis/tardis_portal/tests/filters/test_middleware.py, tardis/tardis_portal/tests/test_models.py, tardis/tardis_portal/views.py
=> a number of small fixes

tardis/tardis_portal/api.py
=> streaming single files

tardis/tardis_portal/templates/tardis_portal/ajax/datafile_list.html
=> showing online files without archive tooltip now

tardis/tardis_portal/auth/authservice.py
granted for new users, e.g. users imported from LDAP.
=> Adding permissions required for "Add files..." to default permissions

build.sh, requirements.txt
I was unable to pip install python-ldap on Ubuntu 14.04 without these -dev packages.
=> Add some apt-get dependencies so python-ldap will compile.

docs/install.rst, requirements-centos.txt
And added package requirements for centos.
=> Update installation instructions for CentOS 7.

tardis/tardis_portal/api.py
Following the pattern from #520, I changed a few more API calls
=> Speed up api

tardis/apps/publication_forms/default_settings.py, tardis/apps/publication_forms/doi.py, tardis/apps/publication_forms/email_text.py, tardis/apps/publication_forms/pub_form_config.py, tardis/apps/publication_forms/tasks.py, tardis/apps/publication_forms/utils.py, tardis/apps/publication_forms/views.py
* reformatting (autopep8, etc.) and refactoring (many functions extracted from the process_form view function)
* improved logging
* emails to authors also CC'd to admins
=> pub form views fn refactored, user emails cc'd to admins, better logging

tardis/tardis_portal/templates/tardis_portal/about.html
This addresses issue https://github.com/mytardis/mytardis/issues/563
=> Change to contact email on About page as requested by AK.

tardis/tardis_portal/templates/tardis_portal/about.html
=> Revert "Change to contact email on About page as requested by AK."

tardis/tardis_portal/download.py, tardis/tardis_portal/models/datafile.py, tardis/tardis_portal/tests/test_download.py, tardis/tardis_portal/tests/test_tar_download.py, tardis/test_settings.py
usually caused by too long file or experiment or other names
=> fixes bug that would send wrong tar size in some situations

tardis/tardis_portal/api.py
associated with a schema id or namespace.
=> Adding filters to allow retrieving the list of parameter names

tardis/tardis_portal/models/storage.py
as discussed in #370 obsoletes #556
=> Default storage box mechanics

tardis/default_settings.py
=> default site title

tardis/tardis_portal/models/storage.py
now properly returns pickled option values when queried
=> storage box option bugfix

tardis/tardis_portal/views/pages.py
This fixes some bugs to PR https://github.com/mytardis/mytardis/pull/576 introduced here https://github.com/mytardis/mytardis/commit/34f0cc1ca35c9885225cb5940ee4f7f984b3645e .
=> Bugfix for overriding index view from settings

tardis/tardis_portal/models/parameters.py, tardis/tardis_portal/tests/test_models.py, tardis/tardis_portal/tests/test_parametersetmanager.py
refactored #533 
Please have a look @pansapiens
=> Make Parameter.set_value handle LINK data_types take 2

docs/changes.rst, tardis/tardis_portal/api.py, tardis/tardis_portal/models/datafile.py, tardis/tardis_portal/models/storage.py, tardis/tardis_portal/tasks.py
Newer versions of celery will remove the method task contrib and it's proven to cause issues occasionally, so I removed it.
=> Refactoring method tasks

docs/changes.rst, tardis/tardis_portal/auth/decorators.py, tardis/tardis_portal/managers.py, tardis/tardis_portal/templates/tardis_portal/ajax/access_list_group.html, tardis/tardis_portal/templates/tardis_portal/ajax/share.html, tardis/tardis_portal/templates/tardis_portal/form_template.html, tardis/tardis_portal/tests/test_authorisation.py, tardis/tardis_portal/views/authorisation.py
Single commit version of https://github.com/mytardis/mytardis/pull/599, resolves merge conflict.
=> Allow groups to 'own' an Experiment

tardis/default_settings.py, tardis/tardis_portal/templates/base.html, tardis/urls.py
Add a base html template and use the default registration form.
=> User registration fix

docs/apps/publication_forms.rst, tardis/apps/publication_forms/views.py
These are some docs for the publication form. Not to be merged just yet; submitting now for review, and in particular for @pansapiens to take a look and add his notes since he has been most recently developing/deploying this feature.
=> Pub form docs

tardis/tardis_portal/tasks.py
left over from refactoring method tasks
=> bugfix for ingest task

tardis/apps/publication_forms/default_settings.py, tardis/apps/publication_forms/pub_form_config.py, tardis/apps/publication_forms/static/publication-form/default-form.html, tardis/apps/publication_forms/views.py
For each dataset to be included in a publication that does not have a specific extra information form, a generic free-text description box will be displayed. This replaces the previous behaviour of not collecting any additional information.
=> Generic dataset description for publication workflow

tardis/apps/push_to/migrations/0002_auto_20160518_1953.py, tardis/apps/push_to/tasks.py, tardis/apps/push_to/views.py
This PR adds a missing migration and fixes path creation on the remote system
=> Push to updates 18 may

tardis/apps/deep_storage_download_mapper/mapper.py, tardis/tardis_portal/download.py, tardis/tardis_portal/forms.py, tardis/tardis_portal/models/datafile.py, tardis/tardis_portal/tests/test_download.py, tardis/tardis_portal/tests/test_models.py, tardis/tardis_portal/tests/test_tar_download.py, tardis/tardis_portal/tests/test_views.py, tardis/tardis_portal/util.py
Some sanitation and some tests.
Did I miss any important use of dataset.description?
=> Safe dataset names

tardis/analytics/ga.py, tardis/analytics/tracker.py, tardis/default_settings.py, tardis/tardis_portal/context_processors.py, tardis/tardis_portal/download.py, tardis/tardis_portal/sftp.py
Track downloads and SFTP sessions with Google analytics
=> Better analytics

tardis/tardis_portal/templates/tardis_portal/view_dataset.html, tardis/tardis_portal/templates/tardis_portal/view_experiment.html
=> change push-to button colour

tardis/tardis_portal/templates/tardis_portal/view_dataset.html
This PR hides the preview images section of the dataset view in cases where no preview images are present.
=> hide preview image section if no images present

tardis/tardis_portal/download.py, tardis/tardis_portal/models/datafile.py
Downloads from S3 should work with this change
=> Non disk downloads

docs/admin/auth_ldap.rst, tardis/tardis_portal/auth/ldap_auth.py
See also: https://bitbucket.org/mytardis/storedotmonash-salt-pillars/pull-requests/14/changes-to-prepare-for-decommissioning-of/diff
=> LDAP changes for decommissioning of directory.monash.edu.au

requirements.txt
lets celery choose its compatible kombu version
=> fixing CI build

tardis/tardis_portal/templates/tardis_portal/about.html
- Removing Steve Androulakis,
- Adding link to http://www.mytardis.org/
- Allowing custom support email address, configured in settings.py
=> Changes to About page:

tardis/tardis_portal/auth/ldap_auth.py
the same directory have different organizational units.
=> LDAP fix for case where different MyTardis users binding against

Dockerfile-base, install-ubuntu-requirements.sh, requirements-base.txt, requirements-osx.txt
None of these are used anywhere
=> Removing unused dependencies

tardis/tardis_portal/templates/tardis_portal/user_guide.html
Formats the <iframe> tag correctly so that the portal_template html works correctly.
Ref. issue mytardis/mytardis#616
=> Fix for issue #616: menu dropdown not working on help page.

tardis/tardis_portal/templates/tardis_portal/facility_overview.html
Moved the page title 'Facility Overview' to the top and changed the html tags and css class to be consistent with titles on other pages.
=> Refactor page title to be consistent with other pages.

tardis/default_settings/frontend.py, tardis/tardis_portal/templates/tardis_portal/ajax/owned_exps_list.html, tardis/tardis_portal/templates/tardis_portal/ajax/shared_exps_list.html, tardis/tardis_portal/templates/tardis_portal/my_data.html, tardis/tardis_portal/templates/tardis_portal/portal_template.html, tardis/tardis_portal/tests/test_views.py, tardis/tardis_portal/views/ajax_pages.py, tardis/tardis_portal/views/pages.py, tardis/urls.py
See tardis/default_settings/frontend.py's OWNED_EXPS_PER_PAGE and
SHARED_EXPS_PER_PAGE
=> Added pagination to "My Data" view

requirements-base.txt
rdfextras also happens to depend on an old version of pyparsing, causing conflicts
=> removed rdfextras, as it is not being used

requirements-base.txt, requirements-centos.txt, requirements-osx.txt
I combined and tested a few dependency updates
Found #838 but no issues with updates
=> Dependency updates

tardis/tardis_portal/templates/tardis_portal/ajax/owned_exps_list.html, tardis/tardis_portal/templates/tardis_portal/ajax/shared_exps_list.html, tardis/tardis_portal/templates/tardis_portal/my_data.html
experiment links weren't links anymore after #821
=> fixing regression from pagination changes in #821

tardis/tardis_portal/api.py
See here: https://github.com/mytardis/mytardis-app-mydata/pull/9 for the corresponding PR for the mytardis-app-mydata app.  The current stable MyData version POSTs to the /api/v1/dataset_file/ endpoint (from the MyTardis API) when uploading files via POST.  But when uploading via staging, MyData POSTs to the /api/v1/mydata_dataset_file/ endpoint (from the mytardis-app-mydata app's API extensions), so that the approved storage box associated with the MyData instance can be used to return the temp_url to upload to.  Duplicate key errors are much more likely to occur when uploading via POST, because for staging, the DataFile creation response time is much quicker (without the file upload), so it is unlikely that another MyData instance is attempting to create the same DataFile record at the …
=> Respond with 409 for DataFile duplicate key errors, instead of raising an Internal Server Error.

.eslintrc, .jshintrc, tardis/apps/publication_forms/static/publication-form/publication_form.js, tardis/apps/publication_forms/templates/form.html, tardis/apps/publication_forms/views.py, tardis/tardis_portal/templates/tardis_portal/view_experiment.html
Most of these commits should be easy to follow, except for the last one, which implements the controllerAs syntax: 
https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md#style-y030
https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md#style-y031
https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md#style-y032
Not expecting this to be merged quickly, but hoping to trigger a discussion.
=> Making publication_form.js pass AngularJS ESLint stye checks

tardis/default_settings/auth.py
This documents the current behaviour of the REGISTRATION_OPEN setting. In the future I propose this setting should be removed and the UI elements toggled based on the presence absence of the `registration` app in `INSTALLED_APPS`.
=> Update docstring for REGISTRATION_OPEN

tardis/tardis_portal/templates/tardis_portal/login.html, tardis/tardis_portal/templates/tardis_portal/portal_template.html
=> Another fix (hopefully the last one), following on from the recent

tardis/apps/push_to/utils.py
=> Ensuring that bytes_available returns the correct number of bytes

tardis/tardis_portal/models/storage.py, tardis/tardis_portal/tasks.py
… in settings.py to automatically copy data from a storage box marked as "autocache" to faster storage.
=> Adding an autocaching task which can be scheduled with Celerybeat

tardis/apps/push_to/tasks.py
Fix for sanitising data directory path in Push_to app. Fixing issue with pushing files in sub directories.
=> Pushto url fix

tardis/tardis_portal/api.py, tardis/tardis_portal/tests/test_api.py
Adding myself as a module author.
=> Allowing datasets to be queried by instrument.

Dockerfile-test, features/environment.py
=> Ensure that npm install has run before behave/PhantomJS tries

tardis/default_settings/frontend.py, tardis/tardis_portal/views/ajax_json.py
=> List most recent datasets at the top in experiment view, as done

tardis/tardis_portal/views/utils.py
Fix / workaround for https://github.com/mytardis/mytardis/issues/1003
=> Avoid trying to store non-serializable session data

requirements-base.txt
I thought closing pyup-bot's PR for this would cause pyup-bot to automatically rebase and resubmit, but this hasn't happened yet, hence this new PR.
=> Upgrading pyjwt dependency to v1.6.4

docs/requirements.txt
as push_to/requirements.txt was recently removed
=> Removing push_to/requirements.txt from docs/requirements.txt,

tardis/tardis_portal/deprecations.py
=> Only force deprecation-related warnings to be displayed, not

tardis/tardis_portal/context_processors.py, tardis/tardis_portal/templates/tardis_portal/about.html, tardis/tardis_portal/templates/tardis_portal/portal_template.html, tardis/tardis_portal/views/pages.py
Ensuring documentation links point to current version
=> Cherry-pick fix for documentation links

tardis/default_settings/debug.py
=> Making it easier to debug Django template rendering when running

CONTRIBUTING.rst, build.sh, docs/admin/database.rst, docs/admin/install.rst, docs/admin/searchsetup.rst, manage.py, tardis/tardis_portal/tests/filters/test_middleware.py, tardis/tardis_portal/tests/test_createuser.py, tardis/tardis_portal/tests/test_dumpschemas.py, tardis/tardis_portal/tests/test_loadschemas.py, test.sh
MyTardis 4.1 and removed in MyTardis 4.2.  Updated some docs
relating to management commands.
=> Adding manage.py, and scheduling mytardis.py to be deprecated in

requirements-base.txt, tardis/apps/oaipmh/provider/experiment.py
(replacing https://github.com/mytardis/mytardis/pull/1077)
=> Upgrading pyoai to v2.5.0

build.sh, docs/admin/install.rst, docs/dev/tests.rst, tardis/default_settings/static_files.py
Addresses https://github.com/mytardis/mytardis/issues/1121
=> Npm file patterns

tardis/apps/push_to/models.py, tardis/apps/push_to/ssh_authz.py, tardis/apps/push_to/templates/destination_selector.html, tardis/apps/push_to/templates/host_list.html, tardis/apps/push_to/tests/test_models.py
Fixes https://github.com/mytardis/mytardis/issues/1095
=> Fix push to

tardis/apps/push_to/models.py, tardis/apps/push_to/ssh_authz.py, tardis/apps/push_to/templates/destination_selector.html, tardis/apps/push_to/templates/host_list.html, tardis/apps/push_to/tests/test_models.py
Patches regression in Push To (#1095) in `series-3.8`.
=> Patch fix Push To in 3.8

tardis/tardis_portal/templates/tardis_portal/manage_group_members.html, tardis/tardis_portal/views/authorisation.py
and added an extra atomic block as described in
https://docs.djangoproject.com/en/1.8/topics/db/transactions/#django.db.transaction.atomic
This fixes https://github.com/mytardis/mytardis/issues/1005
Ensuring that errors returned by the create_group method are displayed
to the user.
=> Removed explicit transaction rollbacks from create_group method

tardis/apps/deep_storage_download_mapper/mapper.py
Resolves https://github.com/mytardis/mytardis/issues/1083
=> Strings should be encoded before being URL quoted.

tardis/search/views.py, tardis/tardis_portal/MultiPartForm.py, tardis/tardis_portal/ands_doi.py, tardis/tardis_portal/deprecations.py, tardis/tardis_portal/filters/diffractionimage.py, tardis/tardis_portal/management/commands/backupdb.py, tardis/tardis_portal/management/commands/checkhashes.py, tardis/tardis_portal/management/commands/chownexperiment.py, tardis/tardis_portal/management/commands/cleanuptokens.py, tardis/tardis_portal/management/commands/createmysuperuser.py, tardis/tardis_portal/models/parameters.py, tardis/tardis_portal/publish/provider/schemarifcsprovider.py, tardis/tardis_portal/storage/squashfs.py, tardis/tardis_portal/tests/test_ands_doi.py
be removed in 4.0 (instead of 3.11), because there might not
be a MyTardis 3.11
=> Changed deprecation warnings to say that this functionality will

js_tests/tests.html, package-lock.json, package.json
and was bringing in some dependencies labeled as vulnerable by
npm audit
=> Removed qunit-fixture dependency which was not needed for tests,

Dockerfile-base, Dockerfile-test, install-ubuntu-requirements.sh, js_tests/tests.html, package-lock.json, test.sh
ensuring that npm test result is reflected in CI build status
=> Using newer npm version for CI builds,

tardis/tardis_portal/tests/test_api.py, tardis/tardis_portal/tests/test_dumpschemas.py, tardis/tardis_portal/tests/test_loadschemas.py, tardis/tardis_portal/tests/test_views.py
These test fixes will be needed for the new publication workflow, but they don't really belong in the publication workflow pull request, so I'm submitting them in a separate pull request.
=> Pre publication workflow test fixes

tardis/search/views.py
=> Prevent leaking users' names in autocomplete when

tardis/tardis_portal/models/dataset.py
GET /datafile/iiif/1/full/!320,240/0/native.jpg HTTP/1.1" 404
=> Only include verified files in get_images, to reduce 404 errors like

tardis/tardis_portal/templates/tardis_portal/index.html, tardis/tardis_portal/templates/tardis_portal/my_data.html, tardis/tardis_portal/templates/tardis_portal/public_data.html
Ensuring that there's a span with property dc:author in each experiment
in the accordion view, even if the experiment has no authors.
=> Add missing exp author span tags

tardis/tardis_portal/templates/tardis_portal/index.html, tardis/tardis_portal/templates/tardis_portal/public_data.html
even if the only author(s) are empty strings
=> Ensuring that authors section of experiment accordion is non-empty,

tardis/apps/openid_migration/tests/test_migration.py, tardis/apps/openid_migration/views.py, tardis/tardis_portal/views/authentication.py
Some patches for OpenID branch
=> Openid patches

tardis/tardis_portal/iiif.py
image can't be rendered.  Otherwise you can get a whole series of 404 errors when trying to load a page with thumbnails, e.g. if thumbnail generation on the fly is being prevented by RENDER_IMAGE_SIZE_LIMIT.
=> Return an empty response instead of a 404 error when a thumbnail

tardis/apps/sftp/user_menu_modifiers.py
Manage My Account can't be found
=> Default to inserting SSH keys menu item at the beginning if

tardis/tardis_portal/download.py, tardis/tardis_portal/shortcuts.py, tardis/tardis_portal/templates/tardis_portal/ajax/experiment_datasets.html, tardis/tardis_portal/tests/test_download.py
=> Better error messages for attempted downloads

tardis/apps/openid_migration/default_settings.py, tardis/apps/openid_migration/tasks.py, tardis/apps/social_auth/auth/social_auth.py, tardis/default_settings/email.py
- added default from email in default_settings
- Code refractor to set from email in emails sent to users
=> adding default from email and changes to from email in emails sent to users

tardis/apps/social_auth/auth/social_auth.py
=> Site-specific account approved email subject and final line of email

package-lock.json
version in package.json in https://github.com/mytardis/mytardis/pull/1342
=> Forgot to commit package-lock.json after updating blueimp-file-upload

tardis/apps/openid_migration/migration.py, tardis/apps/push_to/views.py, tardis/default_settings/celery_settings.py, tardis/tardis_portal/api.py, tardis/tardis_portal/models/datafile.py, tardis/tardis_portal/models/storage.py, tardis/tardis_portal/tasks.py, tardis/tardis_portal/views/ajax_actions.py
This PR sets up the basic infrastructure (default settings) to be able to use task priorities, but doesn't actually offer much in the way of configurable priorities - that will come later.
=> Task priorities part1

tardis/tardis_portal/tasks.py
sub tasks spawned from the parent task
=> Adding kwargs to tasks so we can specify priority to be passed to

js_tests/tests.html, package-lock.json, package.json, tardis/default_settings/static_files.py, tardis/tardis_portal/jstemplates/tardis_portal/badges/datafile_count.html, tardis/tardis_portal/jstemplates/tardis_portal/badges/dataset_count.html, tardis/tardis_portal/jstemplates/tardis_portal/badges/experiment_count.html, tardis/tardis_portal/jstemplates/tardis_portal/badges/last_updated_badge.html, tardis/tardis_portal/jstemplates/tardis_portal/badges/public_access.html, tardis/tardis_portal/jstemplates/tardis_portal/badges/size.html, tardis/tardis_portal/jstemplates/tardis_portal/dataset_tile.html, tardis/tardis_portal/static/css/default.css, tardis/tardis_portal/static/js/backbone-models.js, tardis/tardis_portal/static/js/jquery/tardis_portal/view_experiment/experiment-tabs.js, tardis/tardis_portal/templates/tardis_portal/facility_overview.html, tardis/tardis_portal/templates/tardis_portal/javascript_libraries.html
Adding sprintf-js, because underscore.string's sprintf is deprecated
Adding ESLint check for backbone-models.js
Fixing underscore.string errors in experiment-tab.js following recent underscore.string upgrade.
=> Replacing badges (being phased out of Bootstrap) with labels

tardis/tardis_portal/static/css/default.css, tardis/tardis_portal/templates/tardis_portal/ajax/datafile_list.html, tardis/tardis_portal/templates/tardis_portal/view_dataset.html
more width to better accommodate many long filenames
=> Making datafile fonts and adjacent buttons smaller and giving their column more width

requirements-test.txt, tardis/apps/oaipmh/server.py, tardis/tardis_portal/api.py, tardis/tardis_portal/iiif.py, tardis/tardis_portal/models/datafile.py
Upgrade pylint, the pylint-django plugin and fix code style issues identified by new version
=> Upgrade pylint, the pylint-django plugin and fix code style issues

.dockerignore, Gruntfile.js, docs/dev/tests.rst, js_tests/tests.html, package-lock.json, package.json, test.sh
Upgrade to grunt-contrib-qunit 3.1 which uses Chromium via Puppeteer instead of PhantomJS.
=> Upgrade grunt contrib qunit

tardis/tardis_portal/forms.py, tardis/tardis_portal/tests/test_authorisation.py, tardis/tardis_portal/views/authorisation.py, tardis/urls/experiment.py
Remove ChangeGroupPermissionsForm and /experiment/.../access_list/change/group/
URL which wasn't used anywhere
=> Remove ChangeGroupPermissionsForm and change-group-acl URL

docs/admin/s3_storage.rst, requirements-base.txt
boxes and storing static assets in S3
=> Add django-storages and boto3 to requirements to support S3 storage

docs/admin/filters.rst, tardis/default_settings/filters.py, tardis/tardis_portal/models/datafile.py, tardis/tardis_portal/tests/test_models.py
Improve exception handling and improve unit test mocking for filters task add some settings to allow disabling filters and changing their task priority.
=> Improve exception handling and improve unit test mocking for apply filters task

assets/js/app/search/components/AdvancedSearchForm.jsx, assets/js/app/search/components/Results.jsx, assets/js/app/search/components/Search.jsx, tardis/apps/search/api.py
This PR aims to fix bugs related to search
=> Search related bug fixes

tardis/tardis_portal/managers.py
This PR aims to fix issue where an experiment under embargo is displayed under public experiment.
=> Public data should not include experiments pending embargo

assets/js/tardis_portal/backbone-models.js, assets/js/tardis_portal/view_experiment/dataset-tiles.js, assets/js/tardis_portal/view_experiment/experiment-tabs.js, assets/js/tardis_portal/view_experiment/init/init.js, js_tests/tests.html
This PR aims to fix an issue where user was not able to transfer dataset from experiment view page
=> Fix issue related to transfer datasets tab on experiment view page

tardis/apps/search/api.py
This PR aims to fix issue STORM-16
=> Do not raise a BadRequest exception when query string is empty

tardis/tardis_portal/download.py
Remove logging at error level of temporary debug log
=> Remove logging at error level of temporary debug log

tardis/apps/search/api.py, tardis/apps/search/documents.py
This PR aims to address elasticsearch performance issue by:
- creating an elasticsearch index on objectacl and 
- remove django query required to find intersection between object acl and experiments.
=> Improving search performance

tardis/apps/search/api.py
This PR aims to fix issue where advance search api was not returning expected response.
=> Fixing advance search api

tardis/apps/search/api.py, tardis/apps/search/documents.py, tardis/apps/search/tests/test_api.py
This PR aims to 
- add tests related to simple search and advance search api
- fix some bugs related to search
=> Search api tests

tardis/apps/search/api.py, tardis/apps/search/tests/test_api.py, tardis/default_settings/search.py
This PR aims to provide settings to filter elasticsearch results by minimum score.
=> Filter search results by minimum score

tardis/apps/push_to/templates/destination_selector.html, tardis/apps/push_to/templates/host_list.html
Add comment explaining why facility bundle is loaded in Push To templates
=> Add comment explaining why facility bundle is loaded in Push To

tardis/tardis_portal/models/dataset.py
Don't bother querying dataset's files for images if SHOW_DATASET_THUMBNAILS is False
=> Don't bother querying dataset's files for images if SHOW_DATASET_THUMBNAILS is False

assets/js/tardis_portal/view_dataset/init.js, tardis/tardis_portal/templates/tardis_portal/ajax/datafile_list.html
filenameSearchHandler function.
=> Ensure that the "filename-search-text" input element can access the

tardis/default_settings/frontend.py, tardis/tardis_portal/models/dataset.py
New setting to define datasets which have too many files to scan for images at response time.
=> New setting to define datasets which have too many files to scan for images at response time.

tardis/tardis_portal/templates/tardis_portal/ajax/group_user_list.html
Fix bug with adding user to group, which must have been introduced during the Bootstrap 3 upgrade.
=> Fix bug with adding user to group

tardis/tardis_portal/api.py
This PR aims to update the Instrument api endpoint to return all instrument for an authenticated user.
=> Instrument api get method should return all instruments

assets/js/app/search/components/AdvancedSearchForm.jsx, assets/js/app/search/components/SimpleSearchForm.jsx, tardis/apps/search/api.py, tardis/apps/search/documents.py
This  PR aims to 
- Fix issue where not all the instruments were listed in dropdown
- Improve indexing time for datafile records
- Change elastic search query related to instrument, so that it filters on instrument id
- hide instrument list field in advance search form if  instruments list is empty
=> Search improvements#1

tardis/tardis_portal/tasks.py
=> Fix ParameterName does not support indexing bug and do some minor

tardis/tardis_portal/api.py, tardis/tardis_portal/tests/api/test_experiment_resource.py, tardis/urls/api.py
=> Expose ExperimentAuthor model in API.

docs/apps/oaipmh.rst, requirements-base.txt, tardis/apps/oaipmh/provider/__init__.py, tardis/apps/oaipmh/provider/base.py, tardis/apps/oaipmh/provider/experiment.py, tardis/apps/oaipmh/server.py, tardis/apps/oaipmh/tests/provider/test_base.py, tardis/apps/oaipmh/tests/provider/test_experiment.py, tardis/apps/oaipmh/tests/test_oai.py, tardis/apps/oaipmh/urls.py, tardis/apps/oaipmh/views.py, tardis/apps/related_info/__init__.py, tardis/apps/related_info/fixtures/related_info_schema.json, tardis/apps/related_info/forms.py, tardis/apps/related_info/jstemplates/related_info/publication.html, tardis/apps/related_info/jstemplates/related_info/website.html, tardis/apps/related_info/models.py, tardis/apps/related_info/settings.py, tardis/apps/related_info/templates/related_info/index.html, tardis/apps/related_info/templates/related_info/index_ro.html, tardis/apps/related_info/tests/test_oaipmh.py, tardis/apps/related_info/tests/tests.py, tardis/apps/related_info/urls.py, tardis/apps/related_info/views.py, tardis/default_settings/apps.py, tardis/default_settings/publication.py
Reintroduce oaipmh and related_info apps which were temporarily
removed, due to a Python 3 incompatibility, which has now been
resolved by forking the pyoai requirement.
=> Reintroduce oaipmh and related_info apps

tardis/apps/search/tests/test_api.py
See: https://github.com/mytardis/mytardis/issues/2098
=> More Python 3.5 unit test fixes

.readthedocs.yml
Add Read The Docs config file, specifying Python version for building docs
=> Add Read The Docs config file, specifying Python version for building docs

tardis/default_settings/localisation.py, tardis/tardis_portal/ParameterSetManager.py, tardis/tardis_portal/models/parameters.py
Prevent DataFile records created during DST time change throwing "ambiguous time" errors.
=> SMD-411 Ambiguous Time Error

tardis/tardis_portal/tasks.py
Perhaps we can configure wait time via settings later on.
=> Scheduled task to remove unverified files after 24 hours

tardis/tardis_portal/templatetags/experiment_tags.py
https://jira.apps.monash.edu/browse/STORM-55
=> Display experiment 'last updated' date/time in local timezone

tardis/tardis_portal/download.py
https://jira.apps.monash.edu/browse/STORM-56
=> Replace special method next() with __next()__

tardis/tardis_portal/api.py, tardis/tardis_portal/models/dataset.py, tardis/tardis_portal/tests/api/test_dataset_resource.py
Also start adding path to tree's dir nodes which will prevent
the need to pass the tree state to the API when populating child nodes.
=> Fix tree-view bug (1 dir deep) and add backend tests.

assets/css/default.css, assets/js/apps/search/__tests__/search.spec.jsx, assets/js/apps/search/components/AdvancedSearchForm.jsx, assets/js/apps/tree_view/components/Header.js, assets/js/apps/tree_view/components/TreeView.jsx, assets/js/apps/tree_view/components/custom-theme.js, assets/js/tardis_portal/manage_group_members/ready.js, tardis/tardis_portal/jstemplates/tardis_portal/badges/datafile_count.html, tardis/tardis_portal/jstemplates/tardis_portal/badges/dataset_count.html, tardis/tardis_portal/jstemplates/tardis_portal/badges/experiment_count.html, tardis/tardis_portal/jstemplates/tardis_portal/badges/size.html, tardis/tardis_portal/jstemplates/tardis_portal/dataset_filter.html, tardis/tardis_portal/jstemplates/tardis_portal/dataset_tile.html, tardis/tardis_portal/templates/tardis_portal/ajax/add_group_result.html, tardis/tardis_portal/templates/tardis_portal/ajax/experiment_description.html, tardis/tardis_portal/templates/tardis_portal/ajax/experiment_latest_dataset.html, tardis/tardis_portal/templates/tardis_portal/ajax/experiment_recent_datasets.html, tardis/tardis_portal/templates/tardis_portal/ajax/exps_list.html, tardis/tardis_portal/templates/tardis_portal/ajax/group_list.html, tardis/tardis_portal/templates/tardis_portal/index.html, tardis/tardis_portal/templates/tardis_portal/login.html, tardis/tardis_portal/templates/tardis_portal/my_data.html, tardis/tardis_portal/templates/tardis_portal/public_data.html, tardis/tardis_portal/templates/tardis_portal/shared.html, tardis/tardis_portal/templates/tardis_portal/view_dataset.html
Reduce opacity of folder icons.
Use black hyperlinks instead of default blue color.
Use badge-info unless there's a good reason to use badge-secondary.
Reduce use of the <strong> tag.
Add some icons.
=> Some style changes.

assets/css/default.css, tardis/tardis_portal/templates/tardis_portal/ajax/experiment_latest_dataset.html, tardis/tardis_portal/templates/tardis_portal/ajax/experiment_recent_datasets.html, tardis/tardis_portal/templates/tardis_portal/ajax/exps_list.html, tardis/tardis_portal/templates/tardis_portal/experiment_tags/experiment_authors.html, tardis/tardis_portal/templates/tardis_portal/index.html, tardis/tardis_portal/templates/tardis_portal/my_data.html, tardis/tardis_portal/templates/tardis_portal/public_data.html, tardis/tardis_portal/templates/tardis_portal/shared.html, tardis/tardis_portal/templates/tardis_portal/view_dataset.html
Remove site-specific CSS which made headings look like Boostrap 2.
=> Improve layout within cards in experiment list views.

tardis/tardis_portal/forms.py, tardis/tardis_portal/templates/tardis_portal/ajax/parameteradd.html, tardis/tardis_portal/templates/tardis_portal/ajax/parameteredit.html, tardis/tardis_portal/views/parameters.py
Rename some form methods which are not datafile-specific.
Improve layout
=> Ensure empty parameterset deleted when last parameter deleted via form.

tardis/tardis_portal/templates/tardis_portal/view_dataset.html
Bootstrap 4 fixes for carousel on dataset view page
=> fix for carousel

assets/js/apps/search/__tests__/__snapshots__/search.spec.jsx.snap, assets/js/apps/search/__tests__/search.spec.jsx, assets/js/apps/search/components/AdvancedSearchForm.jsx, assets/js/apps/search/components/Result.jsx, assets/js/apps/search/components/Results.jsx, assets/js/apps/search/components/SimpleSearchForm.jsx, package-lock.json
This PR aims to to add some functional tests to search components and improve test coverage
=> Improve search tests

package-lock.json, package.json
npm audit fix
npm install jest@25.1.0
More information here: https://github.com/webpack/webpack/issues/10516
=> Fix acorn vulnerability using:

assets/js/tardis_portal/backbone-models.js, package-lock.json, package.json
https://jquery.com/upgrade-guide/3.5/#jquery-htmlprefilter-changes
=> JQuery 3.5 related fix

assets/js/tardis_portal/view_dataset/datafile_list/datafile_list.js, tardis/tardis_portal/views/ajax_pages.py
This PR should fix pagination on list view as reported in [MT-387](https://jira.apps.monash.edu/browse/MT-387)
=> fix pagination on datafile list view

assets/js/apps/badges/components/DatasetExperimentCountBadge.jsx, assets/js/apps/badges/components/DatasetViewPageBadges.jsx, assets/js/apps/badges/components/__tests__/DatasetViewPageBadges.spec.jsx, assets/js/apps/tiles/components/DatasetTile.jsx, assets/js/apps/tiles/components/DatasetTiles.jsx, assets/js/apps/tiles/components/DatasetTilesLists.jsx, assets/js/apps/tiles/components/__tests__/DatasetTiles.spec.jsx, assets/js/apps/tiles/index.jsx, assets/js/tardis_portal/view_dataset/file-upload.js, package-lock.json, requirements-base.txt, tardis/tardis_portal/templates/tardis_portal/view_experiment.html, tardis/tardis_portal/views/pages.py
=> [Fix]HSM UI elements should be enabled only when HSM app is enabled

tardis/apps/filepicker/utils.py, tardis/apps/hsm/utils.py, tardis/apps/s3utils/utils.py, tardis/default_settings/__init__.py, tardis/tardis_portal/management/commands/loadschemas.py, tardis/tardis_portal/models/datafile.py, tardis/tardis_portal/tests/api/test_datafile_resource.py, tardis/tardis_portal/tests/slapd.py, tardis/tardis_portal/tests/test_download.py, tardis/tardis_portal/tests/test_publishservice.py, tardis/tardis_portal/tests/test_tar_download.py, tardis/tardis_portal/tests/views/test_upload_views.py, tardis/tardis_portal/views/machine.py, tardis/tardis_portal/xmlwriter.py
Will fix **consider-using-with** error by new version of Pylint.
=> Pylint fixes

tardis/apps/hsm/default_settings.py, tardis/apps/hsm/email_text.py, tardis/apps/hsm/tasks.py
This PR aims to:
- implement a feature, where a user receives an acknowledgement email once he request for datafile recall.
=> [SDM-814] send datafile recall acknowledgement email to logged in user

docs/apps/hsm.rst
This PR aims to :
-    provide admin docs to setup HSM app
=> docs for HSM app
