mytardis/mytardis

- tardis/tardis_portal/templates/tardis_portal/manage_user_account.html
The manage account page (/accounts/manage) requires an action attribute in the form tag to prevent angular from aborting the submission. This is a result of including angular.js in portal_template.html
> manage account form fix

- build.sh
- tardis/settings_changeme.py
- tardis/test_settings.py
To fix issue https://github.com/mytardis/mytardis/issues/281
Removed hard-coded secret key and added doc for how to generate one on the fly.
Example command to execute added to build.sh. Command generates a SECRET_KEY for settings.py and either adds it if the file exists or creates a new settings.py with the key if it doesn't.
> SECRET_KEY removed from settings

- tardis/apps/publication_forms/views.py
- tardis/tardis_portal/templates/tardis_portal/view_experiment.html
- tardis/tardis_portal/views.py
this *should* solve a problem with selecting datasets from experiments shared by a role account and not directly owned by the user.
> publication form and shared experiments

- tardis/settings_changeme.py
* Unneeded middleware in `settings_changeme.py` break Sqlite in Django 1.6 with a:
`TransactionManagementError: Your database backend doesn't behave properly when autocommit is off. Turn it on before using 'atomic'.`
As soon as the database is accessed.
* Removed another redundant transaction related setting
* Removed 'postgres' as the default username, since sqllite needs none  and the name is misleading
> Old transaction settings removal

- requirements.txt
Critical vulnerability in PyJWT: https://auth0.com/blog/2015/03/31/critical-vulnerabilities-in-json-web-token-libraries/
> Update version constraint on PyJWT

- build.sh
- tardis/apps/publication_forms/pub_form_config.py
- tardis/apps/publication_forms/tasks.py
- tardis/settings_changeme.py
* Memcached added to build.sh as a dependency
* Celery task locking fixed by adding a DB cache backend
* Default cache set to memcached
* Publication form setup checks all Schemas and ParameterNames using get_or_create rather than assuming that no setup is required if a schema exists - addresses cases where new parameter names are added to publication schemas.
* Numerical values from the PDBHelper utility are checked for ValueErrors, for cases where the PDB file contains '?' as an entry instead of a value. Invalid entries are logged and omitted from the parameter set.
> Pub form updates

- build.sh
django.db.utils.OperationalError: no such table: default_cache
so moved it further down in build.sh
> collectstatic can fail with this error:

- tardis/tardis_portal/api.py
MyData assumes that the new record's JSON will be returned
in the HTTP response, e.g. here:
https://github.com/monash-merc/mydata/blob/develop/mydata/DatasetModel.py#L79
Having "always_return_data = True" in the MyTardis API's
DatasetResource class's Meta will achieve this.
Alternatively, MyData could be rewritten to do a separate API lookup
after creating the record, or it could assume that the new record
created has the same content as the JSON POSTed to the API, together
with a new primary key as included in the 'location' header of the
HTTP response.
> When a new dataset is created by POSTing to MyTardis's API,

- tardis/tardis_portal/models/access_control.py
- tardis/tardis_portal/models/experiment.py
- tardis/tardis_portal/static/js/facility_view.js
- tardis/tardis_portal/templates/tardis_portal/facility_overview.html
- tardis/tardis_portal/views.py
It looks like this cherry-picked commit also includes a workaround for an issue where attempting to display Facility Overview failed if you had orphaned datasets (not linked to any experiments), as a result of manually deleting experiments in the Django Admin interface.  (See "parent_experiment" below.)
Here's what it looks like in context:
http://mydata.readthedocs.org/en/latest/user-groups.html#data-uploads-from-instrument-pcs
http://mydata.readthedocs.org/en/latest/_images/FacilityOverviewUserGroups.PNG
> Adding support for listing groups (as well as users) in Facility Overview

- tardis/tardis_portal/templates/tardis_portal/ajax/datafile_list.html
Not sure if it's appropriate to merge this (or a variation of it) into the main MyTardis branch(es), or whether it is too site-specific.  Basically our (facility manager) users said they didn't want their users to be given the false impression that their datafiles had finished uploading to MyTardis by seeing them listed in MyTardis's "My Data" view, when in fact they were still only partially uploaded.  Having the datafiles appear in "My Data" before completing their uploads can result from using the MyTardis's API's staging upload method where the datafile record is created before the actual datafile is uploaded. 
At first our (facility manager) MyTardis users requested that unverified datafiles not appear at all in their users' "My Data" view in MyTardis, but then they changed their …
> Highlight unverified datafiles

- tardis/tardis_portal/api.py
MyData assumes that the new record's JSON will be returned
in the HTTP response, e.g. here:
https://github.com/monash-merc/mydata/blob/develop/mydata/ExperimentModel.py#L210
Having "always_return_data = True" in the MyTardis API's
ExperimentResource class's Meta will achieve this.
> When a new experiment is created by POSTing to MyTardis's API,

- tardis/tardis_portal/api.py
- tardis/urls.py
The JSON returned when querying a storage box now includes the
JSON for the associated options and attributes, by using full=True
in the ToManyField.
> Allowing storage box options and attributes to queried via the API.

- tardis/settings_changeme.py
from other authentication backends.  These notes are just
a stopgap until MyTardis's auth system receives an overhaul.
> Notes on use of LDAP authentication provider and how it differs

- tardis/apps/publication_forms/default_settings.py
- tardis/apps/publication_forms/views.py
This PR adds the ability to change the publication owner upon approval to a designated data administrator account. The practical outcome of this is that the "managedBy" related object in rif-cs resolves to an appropriate person.
Code formatting has also been cleaned up by PyCharm - new code is ~ L659 - L683
To set a designated data administrator, add the PUBLICATION_DATA_ADMIN to settings.py and set to the username of the appropriate user. If not set, or set to None, no changes of ownership occur. If set to an invalid user, no changes occur but an error is logged.
> Optional publication data admin can be set

- tardis/tardis_portal/iiif.py
multi-image TIFF files, resulting in very large (usually black)
images appearing where small thumbnails should appear.
Selecting the first image from the sequence seems to fix the
resizing problem.
> Image resizing for thumbnail generation sometimes fails for

- tardis/tardis_portal/models/datafile.py
- tardis/tardis_portal/tests/test_models.py
Allows creation of an empty (zero size) data file via the API if the JSON request provides an int instead of a string (size = 0 instead of size = '0') and REQUIRE_DATAFILE_SIZES is turned on. Removes an unused variable in the unit tests for the DataFile model, and adds a test to check that zero sized files are possible, but negative sized files aren't.
> Allow empty files

- tardis/tardis_portal/views.py
This is helpful when developing new custom views within an app, but will fall back to showing the default tardis_portal views if a custom view fails in production.
> Raise an exception in DEBUG mode if importing a custom Dataset or Experiment view fails.

- .gitignore
- docs/changes.rst
- docs/install.rst
- tardis/apps/publication_forms/static/publication-form/publication_form.js
- tardis/apps/publication_forms/templates/form.html
- tardis/apps/publication_forms/views.py
- tardis/tardis_portal/api.py
- tardis/tardis_portal/context_processors.py
- tardis/tardis_portal/models/parameters.py
- tardis/tardis_portal/sftp.py
- tardis/tardis_portal/static/js/backbone-models.js
- tardis/tardis_portal/templates/tardis_portal/about.html
- tardis/tardis_portal/templates/tardis_portal/about_include.html
- tardis/tardis_portal/templates/tardis_portal/ajax/dataset_metadata.html
- tardis/tardis_portal/templates/tardis_portal/ajax/experiment_metadata.html
- tardis/tardis_portal/templates/tardis_portal/ajax/parameter_table.html
- tardis/tardis_portal/templates/tardis_portal/index.html
- tardis/tardis_portal/templates/tardis_portal/javascript_libraries.html
- tardis/tardis_portal/templates/tardis_portal/my_data.html
- tardis/tardis_portal/templates/tardis_portal/portal_template.html
- tardis/tardis_portal/templates/tardis_portal/public_data.html
- tardis/tardis_portal/templates/tardis_portal/user_guide.html
- tardis/tardis_portal/templatetags/dataset_tags.py
- tardis/tardis_portal/views.py
These changes enable a few things to be overridden by settings, sometimes in combination with a specific app that provides the relevant static files or templates.
Also, gitignore-ing all but the included apps allows any of your apps to live untouched in their own git repos. Don't worry about submodules, just script your deployment to place additional apps there.
> enabling customisations for different deployments, fixing some details

- tardis/tardis_portal/views.py
Ideally, we would determine the user's time zone from their User record or from their Facility record, but using the server's local timezone seems better than displaying UTC.
> Display Facility View datetimes in localtime, not UTC.

- tardis/tardis_portal/download.py
- tardis/tardis_portal/models/datafile.py
- tardis/tardis_portal/shortcuts.py
- tardis/tardis_portal/templates/tardis_portal/ajax/datafile_list.html
This patch allows unverified files to be downloaded when the query parameter ?ignore_verification_status is supplied. Some logic was moved from DataFile.file_object to DataFile.get_file (since it's better not to add named parameters to a Python @property). 
The method DataFile.get_file_getter was removed since it is unused in code MyTardis and default apps.
> Allow unverified file download

- tardis/tardis_portal/fixtures/cc_licenses.json
"However, this page includes other resources which are not secure".
> Using HTTPS URLs for Creative Commons icons to avoid SSL warning:

- tardis/tardis_portal/templates/tardis_portal/ajax/parameter_table.html
- tardis/tardis_portal/templatetags/lookupfilters.py
https://code.djangoproject.com/ticket/3371
Without this fix, I don't see any data within my table body, i.e. row.key seems to look up a key named "key" instead of the actual column key (e.g. "col1").
Also, I've added the surrounding "tr" and "td" tags, so that the tabular parameter value appears within the overall datafile parameter table (and inherits its CSS), instead of appearing as a separate table.
> row.key for a variable key isn't supported in Django:

- tardis/tardis_portal/templates/tardis_portal/ajax/parameter_table.html
Better fallback formatting of LINK parameters when gfk isn't assigned.
Show floats to 3 decimal places, integers without decimal places. This is primarily to get integers to render without a single decimal place (eg 42 instead of 42.0), but may cause issues for some apps that relied on a default where many decimal places were shown. This could be solved by adding a "precision" attribute to the ParameterName model that specifies the number of decimal places that is sensible for a measurement.
> Better formatting of LINK parameters and numbers in parameter table.

- tardis/tardis_portal/tests/test_collectstatic.py
- tardis/test_settings.py
Test added for Django management command 'collectstatic'.
This test will not (and should not) pass Semaphore CI until PR #504 is merged
> collectstatic test added

- tardis/tardis_portal/auth/ldap_auth.py
The first ldap_search retrieves the DN (from the uid), and the
second search retrieves the attributes needed (mail, givenName).
The givenName attribute sometimes isn't accessible until after
binding with the DN.
See also: Store.Star.Help tickets 6526 and 6528.
and: Django admin email alerts with subject: "[Django] ERROR (EXTERNAL IP): Internal Server Error: /accounts/login/".
> Rerun the ldap search after binding with the DN (distinguished name).

- docs/ref/auth_ldap.rst
- tardis/tardis_portal/auth/authservice.py
- tardis/tardis_portal/auth/interfaces.py
- tardis/tardis_portal/auth/ldap_auth.py
- tardis/tardis_portal/auth/localdb_auth.py
- tardis/tardis_portal/tests/test_ldap.py
- tardis/test_settings.py
is the user's full name (e.g. 'cn' in LDAP), but what we really need is 'first_name' and 'last_name' which can be found in LDAP as 'givenName' and 'sn' respectively.
The main driver for this change is that LDAP users are getting imported into MyTardis with a blank first name and a blank last name, and this causes problems with default experiment titles in MyData e.g. instead of a default experiment title of "Microscope1 - John Smith", the experiment title generated by MyData could be given a title of "Microscope1 - ".  The minimum code change to achieve this is the change to ldap_auth.py below, but it also requires changing the LDAP_USER_ATTR_MAP setting in your settings.py, as demonstrated in test_settings.py below.
> Legacy UserProvider auth code populates 'display' key in user dictionary, which

- tardis/apps/publication_forms/default_settings.py
- tardis/apps/publication_forms/email_text.py
- tardis/apps/publication_forms/tasks.py
- tardis/apps/publication_forms/tests/test_email_templates.py
- tardis/apps/publication_forms/views.py
- tardis/tardis_portal/views.py
Email templates are now configurable in settings, with default templates given in tardis/apps/publication_forms/default_settings.py. These can be overridden in the main settings.py file.
There was a bug where embargoed publications were still shown in experiment listings, although their content remained inaccessible. Embargoed publications are now correctly omitted from public data listings.
> Another round of publication form updates

- tardis/tardis_portal/static/css/default.css
~~Also, set cell width for datafile list table to 'auto' - this prevents layout issues when using Bootstrap Table in the template.~~
> CSS tweak to allow long datafile names to linebreak at underscores.

- docs/api.rst
- requirements.txt
- tardis/settings_changeme.py
- tardis/urls.py
This patch adds Swagger support via tastypie_swagger for automatic documentation of the RESTful API.
The API can be explored at <mytardis_server>/api/v1/swagger
I've also tested this with the mytardis-app-mydata Django app installed and it correctly detects the additional API endpoints added by the app.
The extra dependency, the Django app at https://github.com/concentricsky/django-tastypie-swagger, is actively maintained.
> Swagger support for the RESTful API

- tardis/tardis_portal/api.py
Useful if you are uploading to a receiving storage box, and then
you want to check whether the data has been ingested into the
master storage box yet.
> Including 'location' (i.e. storage box name) in Replica JSON.

- tardis/tardis_portal/models/datafile.py
the answer is in the `can_delete` `StorageBoxAttribute`.
Needed this for fixing tar downloads and this is just a bug fix for this feature.
Duplicate of https://github.com/mytardis/mytardis/pull/568
> delete or no delete, that is the question

- tardis/apps/anzsrc_codes/tests/test_oaipmh.py
- tardis/apps/anzsrc_codes/tests/tests.py
- tardis/apps/oaipmh/tests/provider/test_experiment.py
- tardis/apps/oaipmh/tests/test_oai.py
- tardis/apps/related_info/tests/test_oaipmh.py
- tardis/apps/related_info/tests/tests.py
- tardis/tardis_portal/auth/utils.py
- tardis/tardis_portal/forms.py
- tardis/tardis_portal/management/commands/createsuperuser.py
- tardis/tardis_portal/management/commands/createtokenuser.py
- tardis/tardis_portal/management/commands/createuser.py
- tardis/tardis_portal/models/access_control.py
- tardis/tardis_portal/tests/filters/test_jeolsem.py
- tardis/tardis_portal/tests/filters/test_middleware.py
- tardis/tardis_portal/tests/test_api.py
- tardis/tardis_portal/tests/test_authorisation.py
- tardis/tardis_portal/tests/test_authservice.py
- tardis/tardis_portal/tests/test_iiif.py
- tardis/tardis_portal/tests/test_rmexperiment.py
- tardis/tardis_portal/tests/test_tasks.py
- tardis/tardis_portal/tests/test_views.py
- tardis/tardis_portal/tests/tests.py
- tardis/tardis_portal/views/authentication.py
using signals
still does not add the UserAuthentication to superuser created with the `django.contrib.auth` `createsuperuser` command.
> auto creating user profiles

- tardis/tardis_portal/models/datafile.py
This PR adds a "get_as_temporary_file" method to the DataFile object that creates a standard filesystem temporary file object that can be used with libraries that cannot accept a python File object.
This method was added specifically to address issues with the h5py HDF5 library, which expect a file name to be given. It would, however, allow external filters to process data stored in non-filesystem storage, such as swift/s3.
> Create a temporary file copy of a datafile object

- docs/changes.rst
- docs/contextual_views.rst
- tardis/app_config.py
- tardis/apps/push_to/apps.py
- tardis/tardis_portal/views/pages.py
- tardis/urls.py
This PR extends the current functionality of automatically including URL routing (including API urls) form tardis.apps.* to any installed app that is tardis-specific but not under the tardis.apps namespace. Tardis-specific apps are identified as those that reside under tardis.apps or as any that derive their AppConfig class from tardis.app_config.AbstractTardisAppConfig (which is in itself a subclass of django.apps.AppConfig).
> Tardis app urls

- tardis/tardis_portal/models/parameters.py
This is a minor refactor that moves two special cases where '[Ii]mage' parameters are returned as HTML entities into it's own method. This makes _getParameter a little cleaner and could be a precursor to moving all these instances of returning HTML entities out of the model and into methods on the view where they probably belong.
> Refactor _getParameter to move special cases into their own methods

- tardis/tardis_portal/api.py
Fixes some incorrect parameter names used in the query, otherwise querying ObjectACLs for an experiment via the REST API fails with an exception. It seems this bug was introduced during some optimisation back in September ( https://github.com/mytardis/mytardis/commit/4fbe1518b0dd4fe32557707924b043958dd7b186 ) - it didn't bite me until I tried to run something as a non-superuser.
> Bugfix for reading ObjectACLs of Experiments via the tastypie API.

- docs/contextual_views.rst
- tardis/default_settings.py
I've updated the docs relating to contextual view overrides and turned the associated comments in default_settings.py into docstrings. I've only provided examples of settings for class-based views to encourage their use in preference to view functions.
> Update docs and docstrings for contextual view overrides

- docs/changes.rst
- tardis/tardis_portal/migrations/0007_remove_parameter_string_value_index.py
- tardis/tardis_portal/migrations/0008_string_value_partial_index_postgres.py
- tardis/tardis_portal/models/parameters.py
This patch removes the database index from Parameter.string_value. This allows the field to accept strings longer than ~2000 characters on Postgres. This is required due to a limitation of the default Postgres B-tree index type. A Postgres partial index is added for short strings to ensure typical queries remain efficient.
There are associated two migrations.
1. Update the string_value on all tables derived from the Parameter model to remove the index.
2. Add a new partial index on *parameter tables that have a string_value column such that only strings <= 256 characters are indexed.
> Remove index from string_value, create partial index for short strings on Postgres

- tardis/tardis_portal/api.py
Allow facility managers to query all groups. Return username when facility manager queries user (so code matches behaviour described in docstring).
> Allow facility managers to query group names, and return usernames of any user

- docs/changes.rst
- tardis/tardis_portal/api.py
requiring a change to ACLAuthorization's read_list for datasets
(see https://github.com/mytardis/mytardis/issues/597).
> Allowing ordering in the API for experiments, datasets and datafiles,

- tardis/tardis_portal/migrations/0005_datafile_add_size_int_column.py
This migration can be very long on large databases, and consumes a lot of memory if the iterator isn't used. This PR provides feedback on progress, and reduces memory consumption.
> use iterator for big migration; provide feedback on progress

- docs/changes.rst
- tardis/default_settings.py
- tardis/tardis_portal/models/dataset.py
- tardis/tardis_portal/templates/tardis_portal/experiment_tags/experiment_browse_item.html
- tardis/tardis_portal/templates/tardis_portal/view_dataset.html
- tardis/tardis_portal/views/pages.py
https://github.com/mytardis/mytardis/issues/595
which relates to counting and loading of preview images.  (Not
addressing the is_online part of that issue.)  For a dataset
with 125,550 datafiles, running exists() on the QuerySet takes
a fraction of a second, whereas testing if
get_images.count() > 0
takes several minutes.
Carousel loading time has been improved by limiting the number of
images to 100, using a slice filter.  This limit could be a setting
in settings.py, but I don't think it's worth doing that.
> Addressing the part of Issue

- tardis/default_settings.py
- tardis/tardis_portal/views/pages.py
This fixes some incorrect handling of the RAPID_CONNECT_CONFIG dictionary from settings. Raises an exception if Rapid Connect is turned on and RAPID_CONNECT_CONFIG['authnrequest_url'] is not set.
> Bug fix for handling RAPID_CONNECT_* settings

- tardis/tardis_portal/models/datafile.py
- tardis/tardis_portal/models/dataset.py
- tardis/tardis_portal/models/experiment.py
generated a (small) preview image using a filter and saved it
in a DatafileParameter, then there is no need to exclude that
DataFile from the preview images, even if the original DataFile's
file size is large.  Instead of excluding it, we just need to
ensure that DataFile's get_image_data method doesn't return a
file object for a large file.  It should either return a file
object for a small image file, or None.
> Better use of the RENDER_IMAGE_SIZE_LIMIT setting.  If we have

- tardis/search/search_indexes.py
Avoid errors such as this:
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 716: ordinal not in range(128)
when indexing experiments with haystack for search.
> encode utf-8 for haystack indexing

- build.sh
- tardis/default_settings.py
- tardis/tardis_portal/views/images.py
This pull request fixes some issues with screenshot on the SFTP help page.
libfreetype6-dev is required on Ubuntu for Pillow to render fonts, otherwise screenshot generation fails.
The screenshot now honours SFTP_USERNAME_ATTRIBUTE so that it is consistent with the text instructions on the page.
> Fixes to Cyberduck screenshot

- tardis/tardis_portal/views/authorisation.py
Fix usage of `form.is_valid()` (should be method call). Prior to this fix, `form.is_valid` (pointing to the method, not calling the method) would have always evaluated to `True` even if the form doesn't validate.
> Small fix to user permissions form handling

- tardis/tardis_portal/migrations/0010_auto_20160503_1443.py
- tardis/tardis_portal/models/datafile.py
This goes part of the way to solving slow queries associated with Dataset.get_images() by creating a mimetype field index
> add index to mimetype field

- tardis/tardis_portal/sftp.py
SFTP seems to misbehave with gevent, throwing DatabaseErrors such as
```
DatabaseError: DatabaseWrapper objects created in a thread can only be used in that same thread. The object with alias 'default' was created in thread id 140451766560576 and this is thread id 140451572674800.
```
In cases where gevent is used, setting `allow_thread_sharing` to True seems to do the trick. See [this stack overflow answer](http://stackoverflow.com/questions/13194064/using-celery-on-processes-and-gevent-in-tasks-at-the-same-time/30707837#30707837).
> allow connection sharing with gevent

- docs/apps/publication_forms.rst
- tardis/apps/publication_forms/default_settings.py
- tardis/apps/publication_forms/templates/form.html
- tardis/apps/publication_forms/views.py
* If `PUBLICATIONS_REQUIRE_APPROVAL` is set to False, all publications are automatically approved for release.
* The final page now contains an authorisation checkbox that the user must select for the publication to be accepted.
> Authorisation checkbox on final page, publication approval optional

- tardis/tardis_portal/templates/tardis_portal/ajax/experiment_datasets.html
- tardis/tardis_portal/templates/tardis_portal/ajax/experiment_metadata.html
This PR removed some "Add New..." buttons for publications to encourage changes to be made via the publication form. This is a side-effect of using the experiment model to represent publications.
> remove 'add' buttons from publication view

- tardis/apps/publication_forms/templates/form.html
The intro/conditions page of the publication form used to say "Save and continue" even though there is nothing at this point to actually save. The button now reads "Accept and continue".
> Show an 'accept' button on the first page of the publication form

- tardis/default_settings.py
Re-install the missing context processor.
Allows the visibility of the 'Manage Account' page to be controlled via the following setting: MANAGE_ACCOUNT_ENABLED. 
This setting is set to True in the default_settings, and will be set to True by the context processor if the setting is not found.
> Re-install missing context processor: manage_account_processor

- requirements.txt
I'm rebasing the rsacert branch in my paramiko fork for the certificates PR I have with them. This branch change ensures pushes based on the latest paramiko code will not break tardis deployments in the mean time.
> use alternative paramiko branch

- requirements.txt
fixing billiard version conflict, celery reqs the right version automatically
> Urgent bugfix for celery

- tardis/urls.py
Corrects some inconsistent user name pattern matching in urls.py that appears to be preventing the sharing dialogue from rendering correctly where user names contain specific characters, as specified in issue #781
> fix user name pattern matching in urls.py

- tardis/tardis_portal/templates/tardis_portal/experiment/list_base.html
The html/css formatting is not correct on the experiment list pages, because the static files are not loaded in  the experiment/list_base.html.
Added the load static from the static files.
> Add static files reference to experiment lists.

- docs/changelog.rst
- tardis/tardis_portal/auth/decorators.py
- tardis/tardis_portal/templates/tardis_portal/ajax/share.html
- tardis/tardis_portal/views/authorisation.py
This reverts a previous change that allowed 'Staff' users to modify any experiment sharing and ownership in the MyTardis web UI. This better follows Django convention, in line with typical expectations from a Django app.
Discussed: https://github.com/mytardis/mytardis/issues/789
Partially reverts a 'feature' added in https://github.com/mytardis/mytardis/pull/599 / https://github.com/mytardis/mytardis/pull/601.
> Revert use of is_staff to allow modifications to experiment ownership

- docs/admin/install.rst
- tardis/apps/deep_storage_download_mapper/mapper.py
- tardis/default_settings/downloads.py
- tardis/tardis_portal/download.py
- tardis/tardis_portal/sftp.py
- tardis/tardis_portal/tests/test_download.py
- tardis/tardis_portal/tests/test_tar_download.py
- tardis/tardis_portal/util.py
- tardis/tardis_portal/views/pages.py
- tardis/tardis_portal/views/utils.py
There are various places where urllib.quote is used with safe='', implying that no characters are safe to leave unencoded, but as mentioned in https://github.com/mytardis/mytardis/issues/819, some characters like spaces are actually safe for file paths within TARs and SFTP views.
The aim of the pull request is to:
1. Add flexibility to tardis/default_settings/downloads.py, so that MyTardis admins can specify which characters they consider to be safe for file paths in TARs and SFTP views.
2. Encourage more use of the "ARCHIVE_FILE_MAPPERS" (which I propose renaming to "DOWNLOAD_PATH_MAPPERS") in both the TAR downloads and the SFTP view.  Using the default ("deep-storage") mapper is nice because it can be configured in settings.py, unlike the hard-coded sanitise_name and dirname_with_id …
> Proposal: More flexible special character handling in TARs and SFTP

- tardis/tardis_portal/templates/tardis_portal/ajax/datafile_list.html
- tardis/tardis_portal/templates/tardis_portal/ajax/experiment_datasets.html
- tardis/tardis_portal/templates/tardis_portal/ajax/experiment_description.html
- tardis/tardis_portal/templates/tardis_portal/ajax/owned_exps_list.html
- tardis/tardis_portal/templates/tardis_portal/ajax/parameters.html
- tardis/tardis_portal/templates/tardis_portal/ajax/shared_exps_list.html
- tardis/tardis_portal/templates/tardis_portal/index.html
- tardis/tardis_portal/templates/tardis_portal/public_data.html
- tardis/tardis_portal/templates/tardis_portal/view_dataset.html
icon-download-alt should have been replaced by fa-download, but in some cases it was
incorrectly replaced by fa-download-alt which doesn't exist in Font Awesome 4.7.0
> Fixing issue triggered by PR 854 (Font Awesome upgrade).

- tardis/tardis_portal/tasks.py
can be run without arguments like ingest_received_files just have
the "tardis_portal." namespace.  The "tardis_portal.storage_box."
namespace is used for tasks which require a storage box ID as their
first argument.
> Fixing autocache's task name. The convention is that tasks which

- tardis/tardis_portal/templates/tardis_portal/view_dataset.html
to slow page loading for large datasets, as discussed here:
https://github.com/mytardis/mytardis/issues/595
Instead of trying to check the status of every file in the dataset
when the page loads, we can have the ajax check only the current
page of displayed files.
Eventually we want a better user experience for tape recalls, but
the "Some or all files in this dataset are archived" warning resulting
from the dataset.is_online check has not proved useful enough to
justify the slow page loading time.
As noted in the linked GitHub issue, it may be possible to
do the dataset.is_online query more efficiently with aggregate /
group by queries, but personally I don't think it's worth the
trouble.
It would be possible to write an asynchronous task to check datasets
periodically and add some …
> Removing dataset.is_online check because it contributes significantly

- tardis/tardis_portal/auth/decorators.py
to a large number of experiments because
get_accessible_experiments_for_dataset is slow because it uses a
for loop instead of a QuerySet filter.  This commit modifies the
get_accessible_experiment_for_dataset method to use a faster method
to get all of the experiments accessible to the current user
containing the given dataset ID.
> Loading of dataset view pages has been slow for users with access

- tardis/tardis_portal/static/js/main.js
As described in Issue 880, the URL was wrong for this AJAX request, resulting in 404 errors which could affect performance and break some search functionality.
> Fix for https://github.com/mytardis/mytardis/issues/880

- tardis/tardis_portal/iiif.py
- tardis/tardis_portal/templates/tardis_portal/ajax/owned_exps_list.html
- tardis/tardis_portal/templates/tardis_portal/ajax/shared_exps_list.html
- tardis/tardis_portal/templates/tardis_portal/index.html
of 5 thumbnails for each dataset leaves a tiny square which when clicked
on shows a 404 or 500 error.
Previously, just the \<img\> tag was hidden, now the \<li\> tag which contains the \<img\> tag is hidden.
The real issue is that libtiff (as used by ImagMagick / Wand) is not equipped to generate thumbnails for some TIFF images, and shouldn't really be attempting this at response time - it should be done asynchronously, e.g. using Bioformats.  But given that Bioformats is not part of the core MyTardis repository yet, the built-in thumbnail generation can remain with workarounds like this until we have time to review it properly.
> Workaround for issue where failing thumbnail generation in the sequence

- tardis/tardis_portal/views/pages.py
where the headings e.g. "25 Experiments You Own" were replaced by
"Experiment You Own" because the context data was not being correctly
supplied to the template.  The pagination objects are not needed
in the "My Data" template itself, only in the ajax-loaded templates
called by the Javascript in the "My Data" template.
> Fix for a bug introduced when pagination was added to "My Data" page,

- tardis/tardis_portal/iiif.py
TIFF formats besides MissingDelegateError and CoderError, e.g.
DelegateError - for a comprehensive list, see
https://github.com/dahlia/wand/blob/master/wand/exceptions.py#L53
So it makes more sense to catch WandException rather than specific
exception classes derived from WandException.
This follows on from https://github.com/mytardis/mytardis/pull/953
> There are other Wand exceptions which can be raised for unrecognized

- README.rst
Drafting a proposed restructuring of MyTardis's GitHub README for the purpose of:
1. Providing links to related projects such as ImageTrove
2. Listing some known deployments
3. Using mytardis.org to provide introductory text, replacing introductory text which was focused on X-Ray crystallography data.
> Readme rewrite

- tardis/tardis_portal/templates/tardis_portal/ajax/choose_rights.html
updates the license text correctly in the Change Public Access dialog.
> When making an experiment public, ensure that selecting a license

- docker-test.yml
Passes `--default-authentication-plugin=mysql_native_password` to MySQL docker test to revert MySQL to use previous authentication behaviour
> Fix for #998

- requirements-base.txt
- requirements-osx.txt
This PR addresses #1000 and #1001:
- Upgrade six to 1.11.0
- Pin html5lib to 0.9999999 for Mac OS X
> Upgrade six and pin html5lib

- requirements-base.txt
For upgrading to Django 1.11, see: https://github.com/mytardis/mytardis/pull/991
> Upgrading Django version (from 1.8.18 to 1.8.19)

- requirements-base.txt
This PR updates django-registration-redux from 1.4 to 1.10. The latest version of django-registration-redux is actually 2.4, but this is not compatible with MyTardis.
> Upgrading django-registration-redux dependency to v1.10

- Dockerfile-base
See also: https://github.com/mytardis/mytardis/pull/1037
> html5lib is now installed from requirements-base.txt instead

- requirements-base.txt
`zeep` was recently included to replace `suds`, but `zeep` requires `isodate>=0.5.4`.
> Upgrade isodate dependency to 0.6.0 to avoid zeep version incompatibility

- requirements-base.txt
Recent upgrade of `requests` to 2.18.4 caused an incompatibility with transitive dep on urllib3:
> requests 2.18.4 has requirement urllib3<1.23,>=1.21.1, but you'll have urllib3 1.23 which is incompatible.
This PR pins `urllib3==1.22` to avoid incompatibility.
> Pin `urllib3==1.22` to satisfy `requests` compatibility requirements

- Dockerfile-build
- Dockerfile-test
- install-ubuntu-requirements.sh
- requirements-base.txt
- requirements-osx.txt
- requirements-postgres.txt
Removes dependency on system package for `psycopg2` for Ubuntu
Upgrades to version 2.7.4
> Switch to installing `psycopg2-binary` via pip

- Dockerfile-build
- Dockerfile-test
- requirements-mysql.txt
This is the package recommended by Django. It was forked from the
existing MySQLdb API driver, which now appears to be unmaintained.
> Switch to `mysqlclient` library as MySQL driver API

- requirements-base.txt
MyTardis tests don't appear to use this at all. Removing it yields same coverage result.
> Remove unused `nosexcover` dependency

- .pylintrc
- requirements-base.txt
- tardis/apps/equipment/south_migrations/0001_initial.py
- tardis/apps/push_to/models.py
- tardis/apps/push_to/oauth_tokens.py
- tardis/tardis_portal/api.py
- tardis/tardis_portal/filters/diffractionimage.py
- tardis/tardis_portal/models/datafile.py
- tardis/tardis_portal/models/experiment.py
- tardis/tardis_portal/publish/provider/schemarifcsprovider.py
- tardis/tardis_portal/shortcuts.py
- tardis/tardis_portal/tasks.py
- tardis/tardis_portal/util.py
- tardis/tardis_portal/views/authentication.py
- tardis/tardis_portal/views/authorisation.py
************* Module tardis.tardis_portal.tasks
W1113:175,0:sbox_copy_files: Keyword argument before variable positional arguments list in the definition of sbox_copy_files function
W1113:187,0:sbox_move_files: Keyword argument before variable positional arguments list in the definition of sbox_move_files function
W1113:245,0:dfo_copy_file: Keyword argument before variable positional arguments list in the definition of dfo_copy_file function
R1710:265,0:dfo_verify: Either all return statements in a function should return an expression, or none of them should.
************* Module tardis.tardis_portal.shortcuts
R1710:65,0:get_experiment_referer: Either all return statements in a function should return an expression, or none of them should.
************* Module tardis.tardis_portal.util …
> Upgrading Pylint to 1.9.1 and addressing these issues:

- .github/ISSUE_TEMPLATE/monthly_issue.md
- .github/ISSUE_TEMPLATE/patch_issue.md
Help release managers to create issues for tracking minor and patch releases.
> Add minor and patch release issue templates to help with releases

- docs/changelog.rst
- package.json
- tardis/__init__.py
`develop` branch should really reflect the version we are currently
working on and should get bumped to the next version when we release.
> Updating `develop` version numbers

- tardis/search/views.py
- tardis/tardis_portal/MultiPartForm.py
- tardis/tardis_portal/ands_doi.py
- tardis/tardis_portal/deprecations.py
- tardis/tardis_portal/filters/diffractionimage.py
- tardis/tardis_portal/management/commands/backupdb.py
- tardis/tardis_portal/management/commands/checkhashes.py
- tardis/tardis_portal/management/commands/chownexperiment.py
- tardis/tardis_portal/management/commands/cleanuptokens.py
- tardis/tardis_portal/management/commands/createmysuperuser.py
- tardis/tardis_portal/models/parameters.py
- tardis/tardis_portal/publish/provider/schemarifcsprovider.py
- tardis/tardis_portal/storage/squashfs.py
- tardis/tardis_portal/tests/test_ands_doi.py
I have marked it as being deprecated in v3.10, which would mean
that the deprecation warnings should appear in v3.8, but it's
up to @keithschulze (as our v3.8 release manager) to decide whether
these deprecation warnings can be included in v3.8, given that
we're in a feature freeze.  If not, I'll update the PR to indicate
that the deprecated code will be removed in v3.11 (not v3.10).
> Marking deprecated functionality.

- tardis/tardis_portal/context_processors.py
- tardis/tardis_portal/templates/tardis_portal/about.html
- tardis/tardis_portal/templates/tardis_portal/portal_template.html
- tardis/tardis_portal/views/pages.py
The MyTardis version (obtained via a git command in ```tardis/default_settings/init.py```) was passed into the about.html template, but we also need it in the portal_template.html template, so the "version" template variable has been moved to the global context processor.
Now that the "Help" link points to http://mytardis.readthedocs.io (rather than locally built documentation), it is important to make it point to the correct version, otherwise clicking "Help" in MyTardis 3.8 will open the documentation for the develop branch with a confusing webpage title like "MyTardis 3.9 documentation".
Each time we tag a new version (e.g. v3.8.0-RC2), we need to activate the readthedocs build for that version.
The readthedocs URLs are case sensitive, and they convert the tag to lower case (e.g. …
> Ensuring documentation links point to current version

- tardis/urls.py
Fixes #1084: Removes `/help` URL
> Patch that Fixes #1084 in series-3.8: Removes `/help` URL

- tardis/default_settings/apps.py
- tardis/tardis_portal/context_processors.py
- tardis/tardis_portal/templates/tardis_portal/javascript_libraries.html
- tardis/tardis_portal/templates/tardis_portal/view_experiment.html
- tardis/tardis_portal/views/pages.py
Disabling the publication_forms app by default and ensuring that
running MyTardis with it disabled doesn't trigger 404 errors
relating to publication_form.css or publication_form.js
> Disabling the publication_forms app by default

- Dockerfile-base
- Dockerfile-test
- build.sh
- docs/admin/install.rst
- docs/changelog.rst
- install-ubuntu-requirements.sh
- requirements-centos.txt
- requirements.txt
Updated docs to indicate that Ubuntu 16.04 and Ubuntu 18.04 are supported,
but Ubuntu 18.04 is recommended.  Removed docs on CentOS installation,
as we don't have time to test it.
> CI builds now run with Ubuntu 18.04.

- package-lock.json
- requirements-base.txt
Removing references to https://github.com/grischa/ in requirements-base.txt
> Replacing grischa forked dependencies

- requirements-base.txt
Regression in latest 19.8 release of gunicorn
`AttributeError: No configuration setting for: disable_access_log_redirection`
> Downgrade gunicorn to previous version because of --log-syslog error

- tardis/default_settings/frontend.py
- tardis/tardis_portal/jstemplates/tardis_portal/dataset_tile.html
- tardis/tardis_portal/views/utils.py
Experiment view's page load time is too slow for large numbers of datasets each containing large numbers of image files, so there needs to be a way to disable dataset thumbnail images until we
have a more efficient way of serving them.  The default value of the new SHOW_DATASET_THUMBNAILS setting preserves the existing behaviour.
> Making dataset thumbnails optional

- tardis/tardis_portal/models/datafile.py
- tardis/tardis_portal/tests/test_models.py
DFO's database record is deleted, but if the DFO's URI is None, then
we shouldn't try to delete the actual file / object, because storage
backends don't support deleting a file / object with a path of None
> Normally the file / object represented by a DFO is deleted before the

- tardis/default_settings/celery_settings.py
- tardis/test_settings.py
because Celery's default of 'amqp://' assumes that you have a
broker like RabbitMQ running.
> Setting BROKER_URL to 'memory://' for local development/testing,

- tardis/apps/push_to/templates/destination_selector.html
- tardis/apps/push_to/templates/host_list.html
- tardis/default_settings/static_files.py
- tardis/tardis_portal/templates/tardis_portal/ajax/access_list_tokens.html
- tardis/tardis_portal/templates/tardis_portal/javascript_libraries.html
- tardis/tardis_portal/templates/tardis_portal/view_dataset.html
to tardis/default_settings/static_files.py, because we don't want
django-npm to add a js/lib/ prefix to everything it copies from
node_modules/ during collectstatic.  Third party dependencies which
are not yet in package.json are still in
tardis/tardis_portal/static/js/lib/
> Reverting change which added an NPM_STATIC_FILES_PREFIX of js/lib/

- requirements-base.txt
because it is not compatible with Python 2.
> Tell pyup-bot that we don't want to upgrade to pylint 2.0.0 yet,

- docs/admin/install.rst
- tardis/apps/push_to/tasks.py
- tardis/celery.py
- tardis/celery_app.py
- tardis/tardis_portal/tasks.py
- tardis/test_settings.py
http://docs.celeryproject.org/en/latest/django/first-steps-with-django.html
We need to add `from __future__ import absolute_import` for Python 2, so
that the `from celery import Celery` import is unambiguous, given that
the celery.py module within the `tardis` project has the same name as
Celery's official celery module.
Changed `tardis_portal_app = Celery("tardis_portal")` to
`tardis_app = Celery("tardis")` to be consistent with `app = Celery('proj')` in
http://docs.celeryproject.org/en/latest/django/first-steps-with-django.html
as "tardis" is the Django project, and "tardis_portal" is the main app
within the project.
Added some docs on configuring services for Systemd, Supervisor.
> Renamed tardis/celery_app.py to tardis/celery.py as recommended by

- requirements-base.txt
> Prevent PyUp-Bot from requesting upgrading pylint-django to v2.0

- tardis/default_settings/templates.py
- tardis/tardis_portal/context_processors.py
- tardis/tardis_portal/templates/tardis_portal/portal_template.html
- tardis/tardis_portal/tests/urls.py
Apps (or their recommended additions to `settings.py`) can add a context processor to `settings.TEMPLATES[0]['OPTIONS']['context_processors']`
which returns a dict with the "user_menu" key, replacing the default user menu.
See: https://github.com/mytardis/mytardis/issues/1189
> Making user menu customizable.

- tardis/apps/anzsrc_codes/tests/test_oaipmh.py
- tardis/apps/related_info/tests/test_oaipmh.py
- tardis/apps/related_info/tests/tests.py
- tardis/tardis_portal/auth/authorisation.py
- tardis/tardis_portal/tests/test_parametersets.py
- tardis/tardis_portal/tests/test_views.py
A model instance specific permissions check for `tardis_acls.change_experiment`
could return True even when the user was missing the `tardis_portal.change_experiment`
permission.
> Fixes: #243. Bug in tardis_acls.change_experiment permissions check

- tardis/default_settings/apps.py
django.contrib.messages.middleware.MessageMiddleware
> django.contrib.messages should be in INSTALLED_APPS in order to use

- tardis/apps/sftp/user_menu_modifiers.py
- tardis/default_settings/apps.py
- tardis/tardis_portal/context_processors.py
permissions of the user associated with the request
> User menu modifiers need the request object so they can check

- tardis/tardis_portal/static/css/default.css
to upgrade to a more recent Bootstrap
> Revert to the heading sizes from Bootstrap 2.0.4, until we have time

- tardis/default_settings/templates.py
- tardis/tardis_portal/templates/tardis_portal/experiment_result.html
Enabling cached template loader: https://docs.djangoproject.com/en/1.11/ref/templates/api/#django.template.loaders.cached.Loader
Fixing a template syntax error identified by manage.py validate_templates
> Template improvements

- tardis/tardis_portal/templates/tardis_portal/portal_template.html
Use message.level_tag instead of message.tags to ensure that
the alert class is correct, e.g. "alert-info"
> Allow HTML in messages marked with extra_tags='safe'.

- tardis/search/search_indexes.py
Haystack docs, but when we try to index the Experiment model's
created_by__username, we get an Internal Server Error saying
'User' object is not iterable when we try to create a new experiment.
> Indexing fields via foreign keys is supposed to work according the

- tardis/tardis_portal/models/datafile.py
Following on from PR https://github.com/mytardis/mytardis/pull/1242, if a preview image parameter is found in the DataFile metadata,
but it refers to a file which doesn't exist, then fall back to
the old default method of generating the thumbnail, which uses
tardis/tardis_portal/iiif.py
> Following on from PR https://github.com/mytardis/mytardis/pull/1242,

- js_tests/jquery/main.test.js
- tardis/default_settings/search.py
- tardis/search/urls.py
- tardis/search/views.py
- tardis/tardis_portal/static/js/main.js
is intended to be partial match (e.g. James) into the search box
and press enter, the Bootstrap typeahead plugin was populating
the search box with a matching user's name from the autcomplete
dropdown, whereas users would expect that pressing enter would
submit the search immediately.
> Removing search autocomplete for now, because if you type what

- tardis/tardis_portal/admin.py
- tardis/tardis_portal/models/facility.py
- tardis/tardis_portal/models/instrument.py
- tardis/tardis_portal/models/storage.py
(UserAuthentication, Facility, Instrument) and setting a default
ordering for the Facility, Instrument and StorageBox models, so
when you're selecting a storage box from a combo-box in Django Admin
they are sorted by storage box name.
> Enhancing MyTardis's Django Admin view by making more models searchable

- tardis/apps/openid_migration/migration.py
fixing an issue where, If an authentication record for old user is updated and if they try to login again a new user record is created
> Fix for multiple ldap account created for same user

- requirements-base.txt
- tardis/default_settings/apps.py
- tardis/default_settings/celery_settings.py
Having followed advice that django-celery was no longer needed,
we had removed both djcelery and kombu.transport.django from the
default INSTALLED_APPS, but for local development, Kombu is
much easier to get up and running than production-worthy brokers
like RabbitMQ, so we are reverting to the old default BROKER_URL
of 'django://'
> Reverting to default BROKER_URL of 'django://' as used in v3.9.

- tardis/tardis_portal/templates/tardis_portal/view_dataset.html
consistent with the Experiment view's "Edit Experiment" button.
Clicking the "Edit Dataset [Description]" button allows editing
other fields besides just the description (e.g. changing the
instrument associated with the dataset).
> Rename "Edit Dataset Description" button to "Edit Dataset" to be

- tardis/apps/openid_migration/migration.py
- tardis/apps/openid_migration/static/js/openid_migration/migrate_accounts.js
- removing change of username post migration
- change displayed new username on migration page to user email address
> Use email address as username for migrated user

- tardis/tardis_portal/models/storage.py
- tardis/tardis_portal/tasks.py
which only have one DFO (i.e. they are not already cached),
and making it send separate dfo_cache_file tasks to separate
Celery workers
> Improving autocache task so it only tries to cache files

- build.sh
Updating the instructions for running ImageMagick v6 via homebrew
on macOS - setting the MAGICK_HOME environment variable may be required.
ImageMagick v7 (the default version installed by brew) still doesn't
seem to play nicely with the Python Wand package, even after Wand's
recent v0.4.5 update.
> Updating the instructions for running ImageMagick v6 via homebrew

- tardis/tardis_portal/tasks.py
to clean up expired Django sessions from the database
> Add a clear_sessions task which we can schedule with celerybeat

- tardis/tardis_portal/templatetags/approved_user_tags.py
The is_authenticated() method should be replaced by the is_authenticated property for Django 1.10 and later
> Use is_authenticated property instead of method for Django 1.10 and later

- docker-ci/docker-test.yml
Use volumes to allow re-running Docker CI tests (after modifying MyTardis code) without rebuilding Docker images.  These volumes were temporarily removed when docker-test.yml was moved into
the docker-ci/ directory.  Now they are being reinstated.
> Use volumes to allow re-running Docker CI tests with modified MyTardis code

- tardis/tardis_portal/models/datafile.py
- tardis/tardis_portal/models/dataset.py
- tardis/tardis_portal/models/experiment.py
- tardis/tardis_portal/models/facility.py
- tardis/tardis_portal/models/instrument.py
- tardis/tardis_portal/tests/api/test_instrument_resource.py
- tardis/tardis_portal/tests/test_models.py
Fix issue where attempting to access an instrument via the REST API without being in the facility manager's group gave an Internal Server Error instead of an Unauthorized error.
> Fix facilities managed by issue

- tardis/tardis_portal/api.py
Ensure that the API schema for each model resource is accessible irrespective
of which user is logged in.  API model resource schemas were already
accessible via Swagger, but some were not available via
`/api/v1/<model-resource-name>/schema/` because of restrictions in
the `ACLAuthorization` class's `read_detail` method.
Also enabled ordering by ID on most model resources, which is useful
for API clients, e.g. as a proxy for creation time ordering.
> Ensure that the API schema for each model resource is accessible

- requirements-base.txt
Better to let celery's pip install decide which billiard version to use
Add newline missing from end of file
> Remove billiard requirement

- assets/js/tardis_portal/index/index.js
- assets/js/tardis_portal/manage_group_members/ready.js
- assets/js/tardis_portal/my_data/my_data.js
- assets/js/tardis_portal/shared/shared.js
- assets/js/tardis_portal/view_dataset/file-upload.js
- assets/js/tardis_portal/view_dataset/ready.js
- assets/js/tardis_portal/view_experiment/activate-tooltips.js
- assets/js/tardis_portal/view_experiment/dataset-tiles.js
- assets/js/tardis_portal/view_experiment/share/share.js
- docker-ci/Dockerfile-base
- docker-ci/Dockerfile-build
- features/steps/create_dataset.py
- js_tests/tardis_portal/main.test.js
- js_tests/tardis_portal/view_experiment/experiment-tabs.test.js
- js_tests/tardis_portal/view_experiment/share.test.js
- tardis/tardis_portal/templates/tardis_portal/index.html
- tardis/tardis_portal/templates/tardis_portal/my_data.html
- tardis/tardis_portal/templates/tardis_portal/shared.html
- tardis/tardis_portal/templates/tardis_portal/view_dataset.html
- test-webpack.config.js
- webpack.config.js
Avoid loading multiple jQuery instances via webpack by removing  …
unnecessary loading of main bundle (outside portal_template), and
by not using Webpack's ProvidePlugin.
This fixes an issue where sometimes the user menu wasn't opening
when clicked (or it was opening and immediately closing), which
appeared to be because multiple event listeners were responding
to the same click event.
> Remove provide plugin

- requirements-base.txt
We don't need urllib3 in requirements-base.txt, better to let pip install requests choose the urllib3 version
> We don't need urllib3 in requirements-base.txt

- features/steps/facility_overview.py
Give the Facility Overview some more time to finish loading in Behave tests
> Give the Facility Overview some more time to finish loading in Behave tests

- tardis/tardis_portal/tasks.py
Add missing kwargs to clear_sessions task, needed to run in celerybeat schedule
> Add missing kwargs to clear_sessions task, needed to run in celerybeat schedule

- assets/js/tardis_portal/view_experiment/experiment-tabs.js
- assets/js/tardis_portal/view_experiment/share/share.js
- tardis/tardis_portal/templates/tardis_portal/ajax/experiment_dataset_transfer.html
- tardis/tardis_portal/templates/tardis_portal/ajax/share.html
- tardis/tardis_portal/templates/tardis_portal/view_experiment.html
Fixes Synchronous XMLHttpRequest warning sometimes seen in experiment view page
This was caused by AJAX content loading scripts.
In ajax/experiment_dataset_transfer.html, render_bundle 'tardis_portal' can be
removed because the 'tardis_portal' bundle has already been loaded in
view_experiment.html
In ajax/share.html, render_bundle 'tardis_portal_view_experiment_share' can be
moved to view_experiment.html, but then we can't use $(document).ready(...) in
share.js.  Instead we call this function expSharingAjaxReady and call it from
experiment-tabs.js after the Sharing tab has been loaded.
> Avoid loading scripts from AJAX content loaded by experiment view page

- tardis/apps/search/api.py
This PR fixes a bug in search API where duplicate records were returned for a given query. Following query was returning result from both experiments and dataset model, as description field is available in both models
``query_dataset = Q("match", description=query_text)``
> explicitly specify index so it searches within that index only

- package.json
- test.sh
so we don't get an old insecure js-yaml version installed as a
downstream dependency of another dev dependency.
> Run npm audit in CI tests and include js-yaml in devDependencies,

- assets/js/tardis_portal/view_experiment/experiment-tabs.js
- assets/js/tardis_portal/view_experiment/init/init.js
- assets/js/tardis_portal/view_experiment/share/share.js
- js_tests/tardis_portal/view_experiment/experiment-tabs.test.js
- tardis/tardis_portal/templates/tardis_portal/view_experiment.html
Directly call a function to load tab pane content instead of using
Javascript events.  Use event.preventDefault() anchor click handlers.
Use data-url rather than href to store AJAX URL. Previously one href
(AJAX URL) was being overwritten by another one.
> Experiment tabs fixes

- tardis/tardis_portal/templates/tardis_portal/ajax/parameteradd.html
- tardis/tardis_portal/templates/tardis_portal/ajax/parameteredit.html
- tardis/tardis_portal/templates/tardis_portal/view_dataset.html
Now that the Add/Save submit button is inside the form, we don't
need Javascript code to submit the form.
> Fix duplicate dataset metadata form submission

- requirements-base.txt
- tardis/apps/search/documents.py
This PR updates django-elasticsearch-dsl library to latest version and includes changes related to document class for elastic search indexing
> Upgrade django-elasticsearch-dsl library to 6.4.2

- tardis/apps/sftp/user_menu_modifiers.py
- tardis/tardis_portal/context_processors.py
This PR aims to fix issue where a a user pending admin approval was able to download api keys and manage SSH keys
> Unapproved user should not be able to download api key and manage SSH keys

- tardis/tardis_portal/templates/tardis_portal/ajax/parameters.html
> Add missing btn-default, required in Bootstrap v3 to ensure that

- assets/js/tardis_portal/view_experiment/share/share.js
- tardis/tardis_portal/templates/tardis_portal/ajax/access_list_group.html
- tardis/tardis_portal/templates/tardis_portal/ajax/access_list_user.html
- tardis/tardis_portal/tests/test_authorisation.py
- tardis/tardis_portal/views/authorisation.py
The previous commit attempted a minimal patch, retaining the
existing behaviour where even AJAX errors still returned an HTTP
status code of 200 (SUCCESS), but it's better to use different
status codes for success (200) and error (400) when adding/removing
users/groups from ObjectACLs.
> Experiment sharing dialog fixes

- requirements-base.txt
- tardis/tardis_portal/api.py
We were previously using a fork of v0.14.0, with a small change here:
https://github.com/mytardis/django-tastypie/commit/e97e02bfb48ad4d0150ff94090ec1bc5c8d6851b
> Switch to an official version of django-tastypie.

- tardis/tardis_portal/api.py
Unauthenticated users don't need to be able to list storage box resources
We were already hiding the sensitive options - everything except "location",
and we were already requiring authentication for read_detail.
> Unauthenticated users don't need to be able to list storage box resources

- tardis/tardis_portal/views/ajax_json.py
that the Dataset model can include objects which support str()
but can't be directly encoded by DjangoJSONEncoder or JSONEncoder.
> Add default=str when using json.dumps with DjangoJSONEncoder, so

- requirements-base.txt
It was forked because I thought it wasn't Python 3 compatible,
but the real problem was http://bugs.python.org/issue19846
which can be resolved by setting ENV LANG C.UTF-8 in our
Dockerfile to ensure that Python 3 has a sensible default encoding.
> Switch back to official version of pyoai.

- package.json
React components will have a '.jsx' extension and be linted with
a different ESLint config, based on
https://github.com/airbnb/javascript/tree/master/react
> Only use jQuery ESLint config for files with '.js' extension.

- .github/ISSUE_TEMPLATE/release_template.md
Rename release template and update it to indicate that we are not
doing monthly releases at present.  Internally, we release more
often using Jenkins/Kubernetes CI/CD.  Community releases are
less frequent at the moment.
> Rename release template

- .github/workflows/mytardis-matrix-test.yml
Github action will allow us to test Mytardis against different python versions
- Currently this is configured to run tests against python ['3.5', '3.6', '3.7', '3.8'] on [push, pull_requests]
- This will also run pylint
> use github action to test Mytardis

- tardis/apps/sftp/api.py
- tardis/apps/sftp/static/js/sftp/sftp.js
- tardis/tardis_portal/tests/api/test_list_api_endpoints.py
The 'sftp/key' resource name was sometimes triggering errors from lxml:
django.request ERROR    Internal Server Error: /api/v1/
Traceback (most recent call last):
...
File "/usr/local/lib/python3.6/dist-packages/tastypie/serializers.py", line 347, in to_etree
element = Element(name or 'object')
File "src/lxml/etree.pyx", line 3019, in lxml.etree.Element
File "src/lxml/apihelpers.pxi", line 101, in lxml.etree._makeElement
File "src/lxml/apihelpers.pxi", line 1721, in lxml.etree._tagValidOrRaise
ValueError: Invalid tag name 'sftp/key'
> The 'sftp/key' resource name was sometimes triggering errors from lxml

- assets/js/tardis_portal/view_experiment/share/licenses.js
- assets/js/tardis_portal/view_experiment/share/public_access_events.js
- assets/js/tardis_portal/view_experiment/share/share.js
- tardis/tardis_portal/templates/tardis_portal/ajax/choose_rights.html
Fix Confirm button in Change Public Access dialog whose jQuery selector was broken by moving it out of the legal-section div.
Also ensure Confirm button is hidden when the user hasn't selected a
license and ensure that it is disable when the user hasn't ticked
the checkbox.
> Fix Confirm button in Change Public Access dialog

- assets/js/apps/tree_view/components/TreeView.jsx
- assets/js/tardis_portal/view_dataset/file-upload.js
1. Encode URI components when fetching child dirs.
2. Check if node.children is defined before evaluating node.children.length
3. Add a "modified" prop and use it to trigger re-rendering after each file upload
> Tree view fixes

- tardis/apps/sftp/sftp.py
"/app/tardis/apps/sftp/management/commands/sftpd.py", line 6, in <module>
from tardis.apps.sftp import sftp
File "/app/tardis/apps/sftp/sftp.py", line 50, in <module>
connection.allow_thread_sharing = True
File "/usr/local/lib/python3.6/dist-packages/django/db/__init__.py", line 31, in __setattr__
return
setattr(connections[DEFAULT_DB_ALIAS], name, value)
AttributeError: can't set attribute
> Remove connection.allow_thread_sharing, which was causing this error:

- tardis/apps/sftp/default_settings.py
- tardis/apps/sftp/sftp.py
Remove gevent support from MyTardis SFTP due to issues with DB connection sharing across threads
> Remove gevent support from MyTardis SFTP

- tardis/tardis_portal/templates/tardis_portal/ajax/experiment_datasets.html
- tardis/tardis_portal/templates/tardis_portal/view_experiment.html
Make authors font style consistent with exp list view, and use pluralize to ensure that an experiment with no datasets displays "0 Datasets", rather than "0 Dataset".
> Make authors font style consistent with exp list view, and use pluralize

- docker-ci/docker-test.yml
- requirements-base.txt
- tardis/apps/search/api.py
- tardis/apps/search/documents.py
- tardis/apps/search/tests/test_index.py
- tardis/default_settings/search.py
This PR :
- Provides support for Elasticsearch version 7.x in Mytardis
- Replaces deprecated field type with supported field types
- Provides support for parallel bulk indexing to speed up indexing time
- Normalizes Datafile document to speed up datafile indexing
- Provides support for latest version(7.1.1) of django-elasticsearch-dsl library.
> updating django elasticsearch dsl to 7

- tardis/tardis_portal/api.py
- tardis/tardis_portal/tests/api/__init__.py
- tardis/tardis_portal/tests/api/test_datafile_resource.py
The `@transaction.atomic` decorator was doing more harm than good.  A better approach is to do something like this: https://github.com/mytardis/mytardis-app-mydata/commit/e45c68ea17b664280efdbd6ab09928d7bc5ae3a8 but we don't need this change in the core `api.py` so urgently, because its `obj_create` method is not used by MyData, i.e. MyData uses the `mytardis-app-mydata` repository's `api.py` instead.  The DataFile endpoint in the core `api.py` is used when creating DataFile records for indexing data already copied to the permanent storage location, so it may be worth re-looking at this after we roll back the `@transaction.atomic` change.
This reverts commit 0a3dc4d1fbe50792d0ccce4c6f698b96502cc991, reversing
changes made to 5fe42d99d4f052c29da6117ed89027a227296ba8.
> Revert "Merge pull request #2275 from jameswettenhall/avoid-creating-df-without-dfos"

- package-lock.json
- package.json
This doesn't appear to be required for building the webpack bundle, and it was causing `npm audit` to fail.
> Remove image-webpack-loader - it has a vulnerable dependency

- tardis/tardis_portal/views/authorisation.py
This PR aims to fix an issue where
- when a user is added as group admin to a group, the user was shown in the list as a member not an admin
> Fix for Group admin page issue

- tardis/tardis_portal/api.py
- tardis/tardis_portal/auth/decorators.py
I have replaced OR clause with IN to reduce query size.
Previously `get_accessible_datafiles_for_user` decorator would produce query similar to:
```
SELECT ... FROM "tardis_portal_datafile"
INNER JOIN "tardis_portal_dataset" ON
("tardis_portal_datafile"."dataset_id" = "tardis_portal_dataset"."id")
INNER JOIN "tardis_portal_dataset_experiments"
ON ("tardis_portal_dataset"."id" = "tardis_portal_dataset_experiments"."dataset_id")
WHERE (
"tardis_portal_dataset_experiments"."experiment_id" = %s OR
"tardis_portal_dataset_experiments"."experiment_id" = %s OR
"tardis_portal_dataset_experiments"."experiment_id" = %s OR
"tardis_portal_dataset_experiments"."experiment_id" = %s OR
"tardis_portal_dataset_experiments"."experiment_id" = %s OR
"tardis_portal_dataset_experiments"."experiment_id" = %s OR …
```
> Fix get accessible datafiles for user

- docs/admin/task_priorities.rst
- tardis/apps/hsm/api.py
- tardis/celery.py
- tardis/default_settings/celery_settings.py
- tardis/tardis_portal/tests/api/test_datafile_resource.py
- tardis/tardis_portal/tests/models/test_datafile.py
- tardis/tardis_portal/tests/test_copy_move.py
- tardis/test_settings.py
https://docs.celeryproject.org/en/stable/userguide/configuration.html
Celery will still be able to read old configuration files until Celery 6.0.
Afterwards, support for the old configuration files will be removed.
> Update Celery settings to a new format
